import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { autoPosterEngine } from "./server/autoPoster";
import { PostCategory } from "./src/types";

async function startServer() {
  const app = express();
  const PORT = 3000;

  // JSON request parser
  app.use(express.json());

  // 1. Posts API (includes both original 32 articles and auto-generated scheduled posts)
  app.get("/api/posts", (req, res) => {
    try {
      const category = req.query.category as string | undefined;
      let posts = autoPosterEngine.getAllPosts();
      if (category && category !== "all") {
        posts = posts.filter(p => p.category === category);
      }

      res.json({
        success: true,
        count: posts.length,
        data: posts
      });
    } catch (err) {
      console.error("Failed to fetch posts:", err);
      res.status(500).json({ success: false, error: "Internal server error" });
    }
  });

  // 2. Single Post by ID API
  app.get("/api/posts/:id", (req, res) => {
    try {
      const postId = req.params.id;
      const allPosts = autoPosterEngine.getAllPosts();
      const found = allPosts.find(p => p.id === postId);

      if (!found) {
        return res.status(404).json({ success: false, error: "Post not found" });
      }

      res.json({
        success: true,
        data: found
      });
    } catch (err) {
      console.error("Failed to fetch post:", err);
      res.status(500).json({ success: false, error: "Internal server error" });
    }
  });

  // 3. Auto-Posting System Management APIs
  // 3.1 Status & Today's Schedule Slots
  app.get("/api/auto-post/status", (req, res) => {
    try {
      const state = autoPosterEngine.getScheduleState();
      const allPosts = autoPosterEngine.getAllPosts();
      const autoGeneratedCount = allPosts.filter(p => p.id.startsWith("auto-")).length;

      res.json({
        success: true,
        data: {
          ...state,
          totalPostsCount: allPosts.length,
          autoGeneratedCount,
          currentTime: new Date().toISOString()
        }
      });
    } catch (err: any) {
      console.error("Auto-post status error:", err);
      res.status(500).json({ success: false, error: err.message || "Status error" });
    }
  });

  // 3.2 Toggle Auto-Poster ON/OFF
  app.post("/api/auto-post/toggle", (req, res) => {
    try {
      const { enabled } = req.body;
      const current = autoPosterEngine.toggleScheduler(Boolean(enabled));
      res.json({ success: true, enabled: current });
    } catch (err: any) {
      console.error("Toggle auto-poster error:", err);
      res.status(500).json({ success: false, error: err.message });
    }
  });

  // 3.3 Trigger Instant Post (Manual / Test)
  app.post("/api/auto-post/trigger", async (req, res) => {
    try {
      const { category, topic } = req.body;
      const validCategories: PostCategory[] = ["insurance", "wage", "finance", "property", "life"];
      const targetCategory: PostCategory = validCategories.includes(category) ? category : "insurance";

      const created = await autoPosterEngine.triggerInstantPost(targetCategory, topic);
      res.json({ success: true, post: created });
    } catch (err: any) {
      console.error("Instant post generation failed:", err);
      res.status(500).json({ success: false, error: err.message || "Generation failed" });
    }
  });

  // 3.4 Re-Randomize Today's Slots
  app.post("/api/auto-post/reschedule", (req, res) => {
    try {
      const slots = autoPosterEngine.generateTodaySchedule(true);
      res.json({ success: true, slots });
    } catch (err: any) {
      console.error("Reschedule error:", err);
      res.status(500).json({ success: false, error: err.message });
    }
  });

  // 3.5 Delete Auto-Generated Post
  app.delete("/api/auto-post/posts/:id", (req, res) => {
    try {
      const { id } = req.params;
      const deleted = autoPosterEngine.deleteAutoPost(id);
      res.json({ success: deleted });
    } catch (err: any) {
      console.error("Delete auto-post error:", err);
      res.status(500).json({ success: false, error: err.message });
    }
  });

  // 4. Dynamic Sitemap XML
  app.get("/sitemap.xml", (req, res) => {
    try {
      const todayStr = new Date().toISOString().split("T")[0];
      const allPosts = autoPosterEngine.getAllPosts();

      let xml = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n`;
      
      // Main category and portal hubs
      const baseUrls = [
        { loc: "https://www.life-calc.kr/", priority: "1.0", changefreq: "daily" },
        { loc: "https://www.life-calc.kr/?cat=insurance", priority: "0.9", changefreq: "weekly" },
        { loc: "https://www.life-calc.kr/?cat=wage", priority: "0.9", changefreq: "weekly" },
        { loc: "https://www.life-calc.kr/?cat=finance", priority: "0.9", changefreq: "weekly" },
        { loc: "https://www.life-calc.kr/?cat=property", priority: "0.9", changefreq: "weekly" },
        { loc: "https://www.life-calc.kr/?cat=life", priority: "0.9", changefreq: "weekly" },
        { loc: "https://www.life-calc.kr/?cat=calculators", priority: "0.85", changefreq: "weekly" },
        { loc: "https://www.life-calc.kr/?cat=about", priority: "0.8", changefreq: "monthly" }
      ];

      for (const u of baseUrls) {
        xml += `  <url>\n    <loc>${u.loc}</loc>\n    <lastmod>${todayStr}</lastmod>\n    <changefreq>${u.changefreq}</changefreq>\n    <priority>${u.priority}</priority>\n  </url>\n`;
      }

      // Add all posts (including newly auto-published posts)
      for (const p of allPosts) {
        xml += `  <url>\n    <loc>https://www.life-calc.kr/?post=${p.id}</loc>\n    <lastmod>${p.date}</lastmod>\n    <changefreq>weekly</changefreq>\n    <priority>0.8</priority>\n  </url>\n`;
      }

      xml += `</urlset>`;

      res.header("Content-Type", "application/xml; charset=utf-8");
      res.send(xml);
    } catch (err) {
      console.error("Sitemap service error:", err);
      res.status(500).end();
    }
  });

  // 5. RSS Feed for human & AI crawler indexing
  app.get("/rss.xml", (req, res) => {
    try {
      const now = new Date();
      const allPosts = autoPosterEngine.getAllPosts();

      let xml = `<?xml version="1.0" encoding="UTF-8" ?>\n<rss version="2.0">\n<channel>\n`;
      xml += `  <title>생활금융 실전 가이드</title>\n`;
      xml += `  <link>https://www.life-calc.kr</link>\n`;
      xml += `  <description>2026년 4대보험, 급여·퇴직금, 연봉 실수령액, 부동산 세무 및 재테크 실전 정보 가이드</description>\n`;
      xml += `  <language>ko-KR</language>\n`;
      xml += `  <lastBuildDate>${now.toUTCString()}</lastBuildDate>\n`;

      for (const p of allPosts) {
        xml += `  <item>\n`;
        xml += `    <title><![CDATA[${p.title}]]></title>\n`;
        xml += `    <link>https://www.life-calc.kr/?post=${p.id}</link>\n`;
        xml += `    <description><![CDATA[${p.summary}]]></description>\n`;
        xml += `    <category>${p.categoryName}</category>\n`;
        xml += `    <author>contact@life-calc.kr (${p.author})</author>\n`;
        xml += `    <pubDate>${new Date(p.date).toUTCString()}</pubDate>\n`;
        xml += `    <guid>https://www.life-calc.kr/?post=${p.id}</guid>\n`;
        xml += `  </item>\n`;
      }

      xml += `</channel>\n</rss>`;

      res.header("Content-Type", "application/xml; charset=utf-8");
      res.send(xml);
    } catch (err) {
      console.error("RSS service error:", err);
      res.status(500).end();
    }
  });

  // 6. Robots.txt
  app.get("/robots.txt", (req, res) => {
    const robots = `User-agent: *
Allow: /
Sitemap: https://www.life-calc.kr/sitemap.xml
`;
    res.header("Content-Type", "text/plain; charset=utf-8");
    res.send(robots);
  });

  // Vite middleware for development vs Static serving for production
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
