import express from "express";
import path from "path";
import fs from "fs";
import { createServer as createViteServer } from "vite";
import { autoPosterEngine } from "./server/autoPoster";
import { PostCategory } from "./src/types";

async function startServer() {
  const app = express();
  const PORT = 3000;

  // JSON request parser
  app.use(express.json());

  // 1. Posts API (includes both original 32 articles and auto-generated scheduled posts)
  app.get("/api/posts", (req, res) => {
    try {
      const category = req.query.category as string | undefined;
      let posts = autoPosterEngine.getAllPosts();
      if (category && category !== "all") {
        posts = posts.filter(p => p.category === category);
      }

      res.json({
        success: true,
        count: posts.length,
        data: posts
      });
    } catch (err) {
      console.error("Failed to fetch posts:", err);
      res.status(500).json({ success: false, error: "Internal server error" });
    }
  });

  // 2. Single Post by ID API
  app.get("/api/posts/:id", (req, res) => {
    try {
      const postId = req.params.id;
      const allPosts = autoPosterEngine.getAllPosts();
      const found = allPosts.find(p => p.id === postId);

      if (!found) {
        return res.status(404).json({ success: false, error: "Post not found" });
      }

      res.json({
        success: true,
        data: found
      });
    } catch (err) {
      console.error("Failed to fetch post:", err);
      res.status(500).json({ success: false, error: "Internal server error" });
    }
  });

  // 3. Auto-Posting System Management APIs
  // 3.1 Status & Today's Schedule Slots
  app.get("/api/auto-post/status", (req, res) => {
    try {
      const state = autoPosterEngine.getScheduleState();
      const allPosts = autoPosterEngine.getAllPosts();
      const autoGeneratedCount = allPosts.filter(p => p.id.startsWith("auto-")).length;

      res.json({
        success: true,
        data: {
          ...state,
          totalPostsCount: allPosts.length,
          autoGeneratedCount,
          currentTime: new Date().toISOString()
        }
      });
    } catch (err: any) {
      console.error("Auto-post status error:", err);
      res.status(500).json({ success: false, error: err.message || "Status error" });
    }
  });

  // 3.2 Toggle Auto-Poster ON/OFF
  app.post("/api/auto-post/toggle", (req, res) => {
    try {
      const { enabled } = req.body;
      const current = autoPosterEngine.toggleScheduler(Boolean(enabled));
      res.json({ success: true, enabled: current });
    } catch (err: any) {
      console.error("Toggle auto-poster error:", err);
      res.status(500).json({ success: false, error: err.message });
    }
  });

  // 3.3 Trigger Instant Post (Manual / Test)
  app.post("/api/auto-post/trigger", async (req, res) => {
    try {
      const { category, topic } = req.body;
      const validCategories: PostCategory[] = ["work", "property", "finance"];
      const targetCategory: PostCategory = validCategories.includes(category) ? category : "work";

      const created = await autoPosterEngine.triggerInstantPost(targetCategory, topic);
      res.json({ success: true, post: created });
    } catch (err: any) {
      console.error("Instant post generation failed:", err);
      res.status(500).json({ success: false, error: err.message || "Generation failed" });
    }
  });

  // 3.4 Re-Randomize Today's Slots
  app.post("/api/auto-post/reschedule", (req, res) => {
    try {
      const slots = autoPosterEngine.generateTodaySchedule(true);
      res.json({ success: true, slots });
    } catch (err: any) {
      console.error("Reschedule error:", err);
      res.status(500).json({ success: false, error: err.message });
    }
  });

  // 3.5 Delete Auto-Generated Post
  app.delete("/api/auto-post/posts/:id", (req, res) => {
    try {
      const { id } = req.params;
      const deleted = autoPosterEngine.deleteAutoPost(id);
      res.json({ success: deleted });
    } catch (err: any) {
      console.error("Delete auto-post error:", err);
      res.status(500).json({ success: false, error: err.message });
    }
  });

  // 4. Dynamic Sitemap XML
  app.get("/sitemap.xml", (req, res) => {
    try {
      const todayStr = new Date().toISOString().split("T")[0];
      const allPosts = autoPosterEngine.getAllPosts();

      let xml = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n`;
      
      // Main category and portal hubs
      const baseUrls = [
        { loc: "https://www.life-calc.kr/", priority: "1.0", changefreq: "daily" },
        { loc: "https://www.life-calc.kr/?cat=work", priority: "0.9", changefreq: "daily" },
        { loc: "https://www.life-calc.kr/?cat=property", priority: "0.9", changefreq: "daily" },
        { loc: "https://www.life-calc.kr/?cat=finance", priority: "0.9", changefreq: "daily" },
        { loc: "https://www.life-calc.kr/?cat=calculators", priority: "0.85", changefreq: "weekly" },
        { loc: "https://www.life-calc.kr/?cat=sitemap", priority: "0.8", changefreq: "weekly" },
        { loc: "https://www.life-calc.kr/?cat=about", priority: "0.8", changefreq: "monthly" },
        { loc: "https://www.life-calc.kr/?cat=privacy", priority: "0.5", changefreq: "monthly" },
        { loc: "https://www.life-calc.kr/?cat=terms", priority: "0.5", changefreq: "monthly" }
      ];

      for (const u of baseUrls) {
        xml += `  <url>\n    <loc>${u.loc}</loc>\n    <lastmod>${todayStr}</lastmod>\n    <changefreq>${u.changefreq}</changefreq>\n    <priority>${u.priority}</priority>\n  </url>\n`;
      }

      // Add all posts (including newly auto-published posts)
      for (const p of allPosts) {
        xml += `  <url>\n    <loc>https://www.life-calc.kr/?p=${p.id}</loc>\n    <lastmod>${p.date}</lastmod>\n    <changefreq>weekly</changefreq>\n    <priority>0.8</priority>\n  </url>\n`;
      }

      xml += `</urlset>`;

      res.header("Content-Type", "application/xml; charset=utf-8");
      res.send(xml);
    } catch (err) {
      console.error("Sitemap service error:", err);
      res.status(500).end();
    }
  });

  // 5. RSS Feed for human & AI crawler indexing
  app.get("/rss.xml", (req, res) => {
    try {
      const now = new Date();
      const allPosts = autoPosterEngine.getAllPosts();

      let xml = `<?xml version="1.0" encoding="UTF-8" ?>\n<rss version="2.0">\n<channel>\n`;
      xml += `  <title>박과장의 생활경제 노트</title>\n`;
      xml += `  <link>https://www.life-calc.kr</link>\n`;
      xml += `  <description>11년차 직장인이 정리하는 급여, 세금, 부동산, 연금 실전 정보 및 생활 금융 계산기</description>\n`;
      xml += `  <language>ko-KR</language>\n`;
      xml += `  <lastBuildDate>${now.toUTCString()}</lastBuildDate>\n`;

      for (const p of allPosts) {
        xml += `  <item>\n`;
        xml += `    <title><![CDATA[${p.title}]]></title>\n`;
        xml += `    <link>https://www.life-calc.kr/?post=${p.id}</link>\n`;
        xml += `    <description><![CDATA[${p.summary}]]></description>\n`;
        xml += `    <category>${p.categoryName}</category>\n`;
        xml += `    <author>noreply@life-calc.kr (${p.author})</author>\n`;
        xml += `    <pubDate>${new Date(p.date).toUTCString()}</pubDate>\n`;
        xml += `    <guid>https://www.life-calc.kr/?post=${p.id}</guid>\n`;
        xml += `  </item>\n`;
      }

      xml += `</channel>\n</rss>`;

      res.header("Content-Type", "application/xml; charset=utf-8");
      res.send(xml);
    } catch (err) {
      console.error("RSS service error:", err);
      res.status(500).end();
    }
  });

  // 6. Robots.txt
  app.get("/robots.txt", (req, res) => {
    const robots = `User-agent: *
Allow: /
Sitemap: https://www.life-calc.kr/sitemap.xml
`;
    res.header("Content-Type", "text/plain; charset=utf-8");
    res.send(robots);
  });

  // 7. Ads.txt for Google AdSense Crawler
  app.get(["/ads.txt", "/app-ads.txt"], (req, res) => {
    const adsTxt = "google.com, pub-9552509372228899, DIRECT, f08c47fec0942fa0\n";
    res.header("Content-Type", "text/plain; charset=utf-8");
    res.header("Cache-Control", "public, max-age=3600");
    res.send(adsTxt);
  });

  // Vite middleware for development vs Static serving for production
  const renderIndexWithMeta = (req: express.Request, rawHtml: string): string => {
    try {
      const postId = (req.query.p || req.query.post) as string | undefined;
      const calcId = (req.query.calc || req.query.s) as string | undefined;
      const catId = (req.query.cat || req.query.category) as string | undefined;

      if (postId) {
        const post = autoPosterEngine.getAllPosts().find(p => p.id === postId);
        if (post) {
          const postTitle = `${post.title} | 박과장의 생활경제 Q&A`;
          const postDesc = post.summary.replace(/"/g, '&quot;');
          const postUrl = `https://www.life-calc.kr/?p=${post.id}`;

          let modified = rawHtml;
          // Title replacement
          modified = modified.replace(/<title>.*?<\/title>/i, `<title>${postTitle}</title>`);
          // Meta description replacement
          modified = modified.replace(/<meta name="description" content=".*?" \/>/i, `<meta name="description" content="${postDesc}" />`);
          // Canonical replacement
          modified = modified.replace(/<link rel="canonical" href=".*?" \/>/i, `<link rel="canonical" href="${postUrl}" />`);
          // OG replacements
          modified = modified.replace(/<meta property="og:title" content=".*?" \/>/i, `<meta property="og:title" content="${postTitle}" />`);
          modified = modified.replace(/<meta property="og:description" content=".*?" \/>/i, `<meta property="og:description" content="${postDesc}" />`);
          modified = modified.replace(/<meta property="og:url" content=".*?" \/>/i, `<meta property="og:url" content="${postUrl}" />`);
          // Twitter replacements
          modified = modified.replace(/<meta name="twitter:title" content=".*?" \/>/i, `<meta name="twitter:title" content="${postTitle}" />`);
          modified = modified.replace(/<meta name="twitter:description" content=".*?" \/>/i, `<meta name="twitter:description" content="${postDesc}" />`);

          // Schema.org BlogPosting
          const jsonLd = {
            "@context": "https://schema.org",
            "@type": "BlogPosting",
            "headline": post.title,
            "description": post.summary,
            "datePublished": post.date.includes(' ') ? `${post.date.replace(' ', 'T')}+09:00` : `${post.date}T09:00:00+09:00`,
            "dateModified": post.date.includes(' ') ? `${post.date.replace(' ', 'T')}+09:00` : `${post.date}T18:00:00+09:00`,
            "author": {
              "@type": "Person",
              "name": post.author || "박과장",
              "url": "https://www.life-calc.kr/about"
            },
            "publisher": {
              "@type": "Organization",
              "name": "박과장의 생활경제 Q&A",
              "url": "https://www.life-calc.kr"
            },
            "mainEntityOfPage": postUrl
          };
          const jsonLdScript = `\n    <script type="application/ld+json">${JSON.stringify(jsonLd)}</script>`;
          modified = modified.replace('</head>', `${jsonLdScript}\n  </head>`);

          return modified;
        }
      }

      if (calcId) {
        const calcTitle = "2026 실전 금융 & 급여 계산기 모음 | 박과장의 생활경제 노트";
        const calcDesc = "최저임금 주휴수당, 연봉 실수령액, 퇴직금, 부동산 취득세, 중개보수, 대출이자 계산기.";
        const calcUrl = `https://www.life-calc.kr/?calc=${calcId}`;
        let modified = rawHtml;
        modified = modified.replace(/<title>.*?<\/title>/i, `<title>${calcTitle}</title>`);
        modified = modified.replace(/<meta name="description" content=".*?" \/>/i, `<meta name="description" content="${calcDesc}" />`);
        modified = modified.replace(/<link rel="canonical" href=".*?" \/>/i, `<link rel="canonical" href="${calcUrl}" />`);
        return modified;
      }

      if (catId) {
        const catNames: Record<string, string> = {
          work: '직장·급여·퇴직 실전 가이드',
          property: '부동산·세금 실전 가이드',
          finance: '연금·금융·절세 실전 가이드',
          calculators: '실생활 금융 계산기 모음',
          about: '박과장 소개 및 운영 철학',
          privacy: '개인정보처리방침',
          terms: '이용약관',
          sitemap: '사이트맵'
        };
        const catName = catNames[catId] || catId;
        const catTitle = `${catName} | 박과장의 생활경제 노트`;
        let modified = rawHtml;
        modified = modified.replace(/<title>.*?<\/title>/i, `<title>${catTitle}</title>`);
        modified = modified.replace(/<link rel="canonical" href=".*?" \/>/i, `<link rel="canonical" href="https://www.life-calc.kr/?cat=${catId}" />`);
        return modified;
      }
    } catch (e) {
      console.error("Meta injection error:", e);
    }
    return rawHtml;
  };

  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    // Intercept index.html requests for crawlers in dev
    app.use(async (req, res, next) => {
      const isHtmlRequest = req.headers.accept?.includes("text/html") || req.path === "/" || req.path === "/index.html";
      if (isHtmlRequest && !req.path.startsWith("/api") && !req.path.startsWith("/@") && !req.path.includes(".")) {
        try {
          const indexPath = path.join(process.cwd(), "index.html");
          let template = fs.readFileSync(indexPath, "utf-8");
          template = await vite.transformIndexHtml(req.originalUrl, template);
          const finalHtml = renderIndexWithMeta(req, template);
          res.status(200).set({ "Content-Type": "text/html; charset=utf-8" }).send(finalHtml);
          return;
        } catch (e) {
          vite.ssrFixStacktrace(e as Error);
          next(e);
          return;
        }
      }
      next();
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath, { index: false }));
    app.get("*", (req, res) => {
      try {
        const indexPath = path.join(distPath, "index.html");
        const rawHtml = fs.readFileSync(indexPath, "utf-8");
        const finalHtml = renderIndexWithMeta(req, rawHtml);
        res.status(200).set({ "Content-Type": "text/html; charset=utf-8" }).send(finalHtml);
      } catch (err) {
        console.error("Error serving index.html:", err);
        res.sendFile(path.join(distPath, "index.html"));
      }
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
