import React, { useState, useEffect } from 'react';
import { PostCategory, PostItem } from '../types';
import { CATEGORY_META } from '../data/postsData';
import { 
  Bot, 
  Sparkles, 
  Clock, 
  CheckCircle2, 
  AlertCircle, 
  RefreshCw, 
  Play, 
  Power, 
  X, 
  Trash2, 
  ExternalLink, 
  Calendar, 
  Activity, 
  Layers,
  ChevronRight,
  Send
} from 'lucide-react';

interface AutoPostScheduleSlot {
  id: string;
  category: PostCategory;
  categoryName: string;
  categoryIcon: string;
  scheduledTime: string;
  scheduledHour: number;
  scheduledMinute: number;
  scheduledSecond: number;
  status: 'pending' | 'published' | 'failed';
  publishedPostId?: string;
  publishedPostTitle?: string;
  publishedAt?: string;
}

interface ScheduleStateData {
  date: string;
  enabled: boolean;
  intervalHours: number;
  slots: AutoPostScheduleSlot[];
  logs: { timestamp: string; message: string; type: 'info' | 'success' | 'warn' | 'error' }[];
  totalPostsCount: number;
  autoGeneratedCount: number;
  currentTime: string;
}

interface Props {
  isOpen: boolean;
  onClose: () => void;
  onSelectPost: (post: PostItem) => void;
  onPostsUpdated: () => void;
}

export default function AutoPostDashboardModal({ isOpen, onClose, onSelectPost, onPostsUpdated }: Props) {
  const [data, setData] = useState<ScheduleStateData | null>(null);
  const [loading, setLoading] = useState(false);
  const [actionLoading, setActionLoading] = useState(false);
  const [selectedCategory, setSelectedCategory] = useState<PostCategory>('work');
  const [customTopic, setCustomTopic] = useState('');
  const [activeTab, setActiveTab] = useState<'schedule' | 'instant' | 'logs'>('schedule');
  const [feedback, setFeedback] = useState<{ type: 'success' | 'error'; message: string } | null>(null);

  const fetchStatus = async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/auto-post/status');
      const json = await res.json();
      if (json.success && json.data) {
        setData(json.data);
      }
    } catch (err) {
      console.error('Failed to fetch auto post status:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (isOpen) {
      fetchStatus();
      const interval = setInterval(fetchStatus, 15000);
      return () => clearInterval(interval);
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const handleToggle = async () => {
    if (!data) return;
    setActionLoading(true);
    try {
      const res = await fetch('/api/auto-post/toggle', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ enabled: !data.enabled })
      });
      const json = await res.json();
      if (json.success) {
        setFeedback({
          type: 'success',
          message: json.enabled ? '1인칭 자동 포스팅 스케줄러가 활성화되었습니다.' : '스케줄러가 일시 중지되었습니다.'
        });
        await fetchStatus();
      }
    } catch (err: any) {
      setFeedback({ type: 'error', message: '상태 변경에 실패했습니다.' });
    } finally {
      setActionLoading(false);
    }
  };

  const handleReschedule = async () => {
    setActionLoading(true);
    try {
      const res = await fetch('/api/auto-post/reschedule', {
        method: 'POST'
      });
      const json = await res.json();
      if (json.success) {
        setFeedback({
          type: 'success',
          message: '오늘의 3대 핵심 카테고리별 4시간 텀 랜덤 시분초가 새로 배정되었습니다.'
        });
        await fetchStatus();
      }
    } catch (err) {
      setFeedback({ type: 'error', message: '스케줄 재배정에 실패했습니다.' });
    } finally {
      setActionLoading(false);
    }
  };

  const handleInstantPost = async () => {
    setActionLoading(true);
    setFeedback(null);
    try {
      const res = await fetch('/api/auto-post/trigger', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          category: selectedCategory,
          topic: customTopic.trim() || undefined
        })
      });
      const json = await res.json();
      if (json.success && json.post) {
        setFeedback({
          type: 'success',
          message: `"${json.post.title}" 1인칭 실전 포스팅이 성공적으로 생성 및 발행되었습니다!`
        });
        setCustomTopic('');
        await fetchStatus();
        onPostsUpdated();
      } else {
        setFeedback({ type: 'error', message: json.error || '포스팅 생성에 실패했습니다.' });
      }
    } catch (err: any) {
      setFeedback({ type: 'error', message: err.message || '요청 처리 중 오류가 발생했습니다.' });
    } finally {
      setActionLoading(false);
    }
  };

  // Helper to format time remaining or elapsed
  const formatTimeSlot = (slot: AutoPostScheduleSlot) => {
    const hourStr = String(slot.scheduledHour).padStart(2, '0');
    const minStr = String(slot.scheduledMinute).padStart(2, '0');
    const secStr = String(slot.scheduledSecond).padStart(2, '0');
    const displayTime = `${hourStr}:${minStr}:${secStr}`;

    const now = new Date();
    const currentSecs = now.getHours() * 3600 + now.getMinutes() * 60 + now.getSeconds();
    const targetSecs = slot.scheduledHour * 3600 + slot.scheduledMinute * 60 + slot.scheduledSecond;
    const diff = targetSecs - currentSecs;

    let diffText = '';
    if (diff > 0) {
      const hours = Math.floor(diff / 3600);
      const mins = Math.floor((diff % 3600) / 60);
      diffText = `${hours > 0 ? `${hours}시간 ` : ''}${mins}분 후 발행 예정`;
    } else {
      diffText = '시간 경과 (완료됨)';
    }

    return { displayTime, diffText, isPast: diff <= 0 };
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/60 backdrop-blur-xs animate-fadeIn">
      <div className="bg-white rounded-3xl border border-slate-200 shadow-2xl w-full max-w-3xl max-h-[90vh] flex flex-col overflow-hidden">
        
        {/* Modal Header */}
        <div className="p-5 sm:p-6 bg-gradient-to-r from-slate-950 via-indigo-950 to-slate-900 text-white flex items-center justify-between border-b border-slate-800">
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 rounded-2xl bg-indigo-500/20 border border-indigo-400/30 flex items-center justify-center text-indigo-400 text-xl">
              👨‍💼
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="font-heading font-black text-base sm:text-lg">
                  박과장의 1인칭 자동 포스팅 엔진
                </h3>
                {data?.enabled ? (
                  <span className="bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 text-[11px] font-bold px-2 py-0.5 rounded-full flex items-center gap-1">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
                    가동 중
                  </span>
                ) : (
                  <span className="bg-slate-700 text-slate-300 text-[11px] font-bold px-2 py-0.5 rounded-full">
                    일시정지
                  </span>
                )}
              </div>
              <p className="text-xs text-slate-400 mt-0.5">
                매일 랜덤 시분초에 3대 핵심 카테고리별 1회씩 4시간 텀으로 자동 발행됩니다.
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-2 text-slate-400 hover:text-white rounded-xl hover:bg-slate-800 transition cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Navigation Tabs & Top Controls */}
        <div className="bg-slate-50 px-5 sm:px-6 py-3 border-b border-slate-200 flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center space-x-1.5 bg-slate-200/70 p-1 rounded-xl text-xs font-semibold">
            <button
              onClick={() => setActiveTab('schedule')}
              className={`px-3 py-1.5 rounded-lg transition cursor-pointer ${
                activeTab === 'schedule' ? 'bg-white text-indigo-700 shadow-2xs font-bold' : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              오늘의 4시간 텀 타임라인
            </button>
            <button
              onClick={() => setActiveTab('instant')}
              className={`px-3 py-1.5 rounded-lg transition cursor-pointer flex items-center gap-1 ${
                activeTab === 'instant' ? 'bg-white text-indigo-700 shadow-2xs font-bold' : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              <Sparkles className="w-3.5 h-3.5" />
              1인칭 즉시 생성 테스트
            </button>
            <button
              onClick={() => setActiveTab('logs')}
              className={`px-3 py-1.5 rounded-lg transition cursor-pointer ${
                activeTab === 'logs' ? 'bg-white text-indigo-700 shadow-2xs font-bold' : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              실행 로그
            </button>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handleToggle}
              disabled={actionLoading}
              className={`text-xs px-3 py-1.5 rounded-xl font-bold flex items-center gap-1.5 transition cursor-pointer border ${
                data?.enabled
                  ? 'bg-amber-50 text-amber-800 border-amber-200 hover:bg-amber-100'
                  : 'bg-emerald-600 text-white border-emerald-600 hover:bg-emerald-700'
              }`}
            >
              <Power className="w-3.5 h-3.5" />
              {data?.enabled ? '스케줄러 멈춤' : '스케줄러 시작'}
            </button>

            <button
              onClick={fetchStatus}
              disabled={loading}
              title="새로고침"
              className="p-1.5 text-slate-500 hover:text-indigo-600 bg-white border border-slate-200 rounded-xl hover:bg-slate-50 transition cursor-pointer"
            >
              <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
            </button>
          </div>
        </div>

        {/* Feedback notification */}
        {feedback && (
          <div className={`px-6 py-2.5 text-xs font-medium flex items-center justify-between ${
            feedback.type === 'success' ? 'bg-emerald-50 text-emerald-800 border-b border-emerald-100' : 'bg-rose-50 text-rose-800 border-b border-rose-100'
          }`}>
            <span className="flex items-center gap-1.5">
              {feedback.type === 'success' ? <CheckCircle2 className="w-4 h-4 text-emerald-600" /> : <AlertCircle className="w-4 h-4 text-rose-600" />}
              {feedback.message}
            </span>
            <button onClick={() => setFeedback(null)} className="text-slate-400 hover:text-slate-600">
              <X className="w-3.5 h-3.5" />
            </button>
          </div>
        )}

        {/* Modal Body Content */}
        <div className="flex-1 overflow-y-auto p-5 sm:p-6 space-y-6">
          
          {/* TAB 1: SCHEDULE TIMELINE */}
          {activeTab === 'schedule' && (
            <div className="space-y-5">
              <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-2">
                <div>
                  <h4 className="font-heading font-black text-slate-900 text-sm sm:text-base flex items-center gap-1.5">
                    <Calendar className="w-4 h-4 text-indigo-600" />
                    오늘({data?.date}) 3대 카테고리 4시간 간격 타임라인
                  </h4>
                  <p className="text-xs text-slate-500 mt-0.5">
                    각 카테고리별로 4시간 간격을 두고 무작위 시분초에 자동 발행됩니다.
                  </p>
                </div>

                <button
                  onClick={handleReschedule}
                  disabled={actionLoading}
                  className="text-xs text-indigo-700 bg-indigo-50 border border-indigo-200 px-3 py-1.5 rounded-xl hover:bg-indigo-100 font-bold transition flex items-center gap-1 cursor-pointer"
                >
                  <RefreshCw className="w-3 h-3" />
                  스케줄 시간 랜덤 재배정
                </button>
              </div>

              {/* 3 Category Schedule Timeline Cards */}
              <div className="grid grid-cols-1 gap-3">
                {data?.slots.map((slot, idx) => {
                  const { displayTime, diffText, isPast } = formatTimeSlot(slot);
                  const isDone = slot.status === 'published';
                  const isFailed = slot.status === 'failed';
                  const catMeta = CATEGORY_META[slot.category] || { bg: 'bg-slate-100', border: 'border-slate-200', icon: '💼', name: slot.categoryName };

                  return (
                    <div
                      key={slot.id || idx}
                      className={`p-4 rounded-2xl border transition-all flex flex-col sm:flex-row sm:items-center justify-between gap-3 ${
                        isDone
                          ? 'bg-emerald-50/50 border-emerald-200'
                          : isFailed
                          ? 'bg-rose-50/50 border-rose-200'
                          : 'bg-white border-slate-200 hover:border-indigo-200 shadow-2xs'
                      }`}
                    >
                      <div className="flex items-start sm:items-center space-x-3">
                        <div className={`w-9 h-9 rounded-xl flex items-center justify-center text-base border shrink-0 ${
                          catMeta?.bg || 'bg-slate-100'
                        } ${catMeta?.border || 'border-slate-200'}`}>
                          {catMeta.icon || slot.categoryIcon}
                        </div>

                        <div>
                          <div className="flex items-center gap-2">
                            <span className="font-heading font-black text-slate-900 text-sm">
                              {catMeta.name || slot.categoryName}
                            </span>
                            <span className="text-[11px] font-mono font-bold px-2 py-0.5 rounded-md bg-slate-100 text-slate-700">
                              🕒 {displayTime}
                            </span>
                            <span className="text-[10px] text-slate-400 font-normal">
                              (슬롯 #{idx + 1})
                            </span>
                          </div>

                          {isDone ? (
                            <p className="text-xs text-emerald-800 font-medium mt-1 line-clamp-1">
                              발행 완료: {slot.publishedPostTitle || '포스팅 등록됨'}
                            </p>
                          ) : (
                            <p className="text-xs text-slate-500 font-medium mt-0.5">
                              {data?.enabled ? diffText : '스케줄러 일시정지 상태'}
                            </p>
                          )}
                        </div>
                      </div>

                      <div className="flex items-center space-x-2 shrink-0 self-end sm:self-center">
                        {isDone ? (
                          <span className="text-xs font-bold text-emerald-700 bg-emerald-100/80 px-2.5 py-1 rounded-lg flex items-center gap-1 border border-emerald-200">
                            <CheckCircle2 className="w-3.5 h-3.5" />
                            발행 완료
                          </span>
                        ) : (
                          <span className="text-xs font-bold text-amber-700 bg-amber-50 px-2.5 py-1 rounded-lg flex items-center gap-1 border border-amber-200">
                            <Clock className="w-3.5 h-3.5" />
                            대기 중
                          </span>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>

              {/* Information Banner */}
              <div className="bg-slate-50 rounded-2xl p-4 border border-slate-200 text-xs text-slate-600 space-y-1.5">
                <p className="font-bold text-slate-800 flex items-center gap-1">
                  <span>💡</span>
                  <span>1인칭 실전 포스팅 원리</span>
                </p>
                <p className="leading-relaxed">
                  1. 11년차 박과장 페르소나가 직접 겪은 사연("퇴직금 누락", "복비 협상", "건보료 방어")을 1인칭으로 서술합니다.<br />
                  2. 모든 글은 2026년 법정 기준 표, 3단계 행동 로드맵, 공식 법령 근거를 반드시 포함합니다.<br />
                  3. 백그라운드 타이머가 매 20초마다 스케줄을 감지하여 자동 발행합니다.
                </p>
              </div>
            </div>
          )}

          {/* TAB 2: INSTANT TEST POST */}
          {activeTab === 'instant' && (
            <div className="space-y-5">
              <div>
                <h4 className="font-heading font-black text-slate-900 text-sm sm:text-base flex items-center gap-1.5">
                  <Sparkles className="w-4 h-4 text-indigo-600" />
                  박과장의 1인칭 실전 글 즉시 생성
                </h4>
                <p className="text-xs text-slate-500 mt-0.5">
                  스케줄 시간을 기다리지 않고 3대 핵심 카테고리 중 하나를 선택해 1인칭 실화 글을 즉시 생성합니다.
                </p>
              </div>

              {/* Category Selector */}
              <div className="space-y-2">
                <label className="text-xs font-bold text-slate-700">카테고리 선택</label>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
                  {(['work', 'property', 'finance'] as PostCategory[]).map(cat => {
                    const meta = CATEGORY_META[cat];
                    const isSelected = selectedCategory === cat;
                    return (
                      <button
                        key={cat}
                        type="button"
                        onClick={() => setSelectedCategory(cat)}
                        className={`p-3.5 rounded-xl border text-xs font-bold flex flex-col items-center gap-1.5 transition cursor-pointer ${
                          isSelected
                            ? 'bg-slate-950 text-white border-slate-950 shadow-sm'
                            : 'bg-white text-slate-700 border-slate-200 hover:bg-slate-50'
                        }`}
                      >
                        <span className="text-xl">{meta?.icon}</span>
                        <span className="font-heading">{meta?.name}</span>
                      </button>
                    );
                  })}
                </div>
              </div>

              {/* Custom Topic Input */}
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <label className="text-xs font-bold text-slate-700">작성 주제 (선택 입력)</label>
                  <span className="text-[11px] text-slate-400">비워두면 박과장의 추천 주제로 자동 작성</span>
                </div>
                <input
                  type="text"
                  value={customTopic}
                  onChange={(e) => setCustomTopic(e.target.value)}
                  placeholder="예: 내가 직접 퇴직연금 DB형에서 DC형으로 전환해 1,200만원 수익 더 낸 실전기"
                  className="w-full px-4 py-3 text-xs sm:text-sm rounded-xl border border-slate-200 focus:outline-hidden focus:border-indigo-500 bg-white"
                />
              </div>

              {/* Quick Topic Prompts */}
              <div className="space-y-1.5">
                <span className="text-[11px] font-bold text-slate-500">추천 실전 프롬프트 예시:</span>
                <div className="flex flex-wrap gap-1.5">
                  {[
                    '내가 이직할 때 미사용 연차수당 140만원 전부 받아낸 협상법',
                    '전세 계약 연장 시 보증보험 갱신 안 했다가 겪은 아찔한 실화',
                    '부모님 용돈 드리다 건강보험 피부양자 박탈당할 뻔했던 방어기'
                  ].map((preset, i) => (
                    <button
                      key={i}
                      type="button"
                      onClick={() => setCustomTopic(preset)}
                      className="text-[11px] bg-slate-100 hover:bg-slate-200 text-slate-700 px-2.5 py-1 rounded-lg transition cursor-pointer"
                    >
                      {preset}
                    </button>
                  ))}
                </div>
              </div>

              {/* Trigger Button */}
              <div className="pt-2">
                <button
                  onClick={handleInstantPost}
                  disabled={actionLoading}
                  className="w-full py-3.5 px-4 rounded-xl bg-gradient-to-r from-slate-950 to-indigo-950 hover:from-slate-900 hover:to-indigo-900 text-white font-bold text-xs sm:text-sm flex items-center justify-center gap-2 shadow-md hover:shadow-lg transition cursor-pointer disabled:opacity-50"
                >
                  {actionLoading ? (
                    <>
                      <RefreshCw className="w-4 h-4 animate-spin" />
                      <span>박과장의 실전 경험담 포스팅을 생성 중입니다...</span>
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-4 h-4 text-indigo-300" />
                      <span>{CATEGORY_META[selectedCategory]?.name} 1인칭 포스팅 즉시 생성 & 발행</span>
                    </>
                  )}
                </button>
              </div>
            </div>
          )}

          {/* TAB 3: SYSTEM LOGS */}
          {activeTab === 'logs' && (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <h4 className="font-heading font-black text-slate-900 text-sm sm:text-base flex items-center gap-1.5">
                  <Activity className="w-4 h-4 text-indigo-600" />
                  스케줄러 실시간 실행 기록
                </h4>
                <span className="text-xs text-slate-500">최근 100건 보관</span>
              </div>

              <div className="bg-slate-900 text-slate-200 rounded-2xl p-4 font-mono text-[11px] space-y-2 max-h-80 overflow-y-auto">
                {data?.logs && data.logs.length > 0 ? (
                  data.logs.map((log, idx) => {
                    const timeStr = new Date(log.timestamp).toLocaleTimeString();
                    return (
                      <div key={idx} className="flex items-start gap-2 leading-relaxed">
                        <span className="text-slate-500 shrink-0">[{timeStr}]</span>
                        <span className={
                          log.type === 'success' ? 'text-emerald-400' :
                          log.type === 'error' ? 'text-rose-400' :
                          log.type === 'warn' ? 'text-amber-400' : 'text-slate-300'
                        }>
                          {log.message}
                        </span>
                      </div>
                    );
                  })
                ) : (
                  <p className="text-slate-500">기록된 로그가 없습니다.</p>
                )}
              </div>
            </div>
          )}

        </div>

        {/* Modal Footer Summary */}
        <div className="p-4 sm:p-5 bg-slate-50 border-t border-slate-200 flex flex-wrap items-center justify-between gap-3 text-xs text-slate-600">
          <div className="flex items-center space-x-4">
            <span>
              총 실전 포스트: <strong className="font-num text-slate-900">{data?.totalPostsCount || 10}</strong>편
            </span>
            <span>
              자동 생성 포스트: <strong className="font-num text-indigo-600">{data?.autoGeneratedCount || 0}</strong>편
            </span>
          </div>

          <button
            onClick={onClose}
            className="px-4 py-2 bg-slate-900 hover:bg-slate-800 text-white rounded-xl font-bold transition cursor-pointer"
          >
            닫기
          </button>
        </div>

      </div>
    </div>
  );
}
