import React from 'react';
import { PostItem, CategoryType } from '../types';
import { ALL_BLOG_POSTS, CATEGORY_META } from '../data/postsData';
import { User, Mail, ChevronRight, TrendingUp, Folder, Calculator, ShieldCheck, Heart, Sparkles, BookOpen, Bot, Clock } from 'lucide-react';
import TableOfContents from './TableOfContents';

interface BlogSidebarProps {
  onSelectPost: (post: PostItem) => void;
  onSelectCategory: (cat: CategoryType) => void;
  onNavigateToCalculator: (calcId: string) => void;
  activePost?: PostItem | null;
  posts?: PostItem[];
  onOpenAutoPoster?: () => void;
}

export default function BlogSidebar({
  onSelectPost,
  onSelectCategory,
  onNavigateToCalculator,
  activePost = null,
  posts = ALL_BLOG_POSTS,
  onOpenAutoPoster
}: BlogSidebarProps) {
  // Top 5 popular posts sorted by view count
  const popularPosts = [...posts]
    .sort((a, b) => b.viewCount - a.viewCount)
    .slice(0, 5);

  const categories: { id: CategoryType; name: string; icon: string; count: number; desc: string }[] = [
    { id: 'work', name: '직장·월급·퇴직', icon: '💼', count: posts.filter(p => p.category === 'work').length, desc: '월급명세서, 퇴직금, 주휴수당, 실업급여' },
    { id: 'property', name: '내집·부동산·세금', icon: '🏠', count: posts.filter(p => p.category === 'property').length, desc: '취득세 감면, 전월세 복비, 주담대 상환' },
    { id: 'finance', name: '연금·보험·재테크', icon: '🛡️', count: posts.filter(p => p.category === 'finance').length, desc: '건보료 방어, 조기연금 계산, ISA 절세' }
  ];

  const autoGeneratedCount = posts.filter(p => p.id.startsWith('auto-')).length;

  return (
    <aside className="space-y-6">
      {/* 0. Sticky Table of Contents (Shown on desktop when viewing an article) */}
      {activePost && (
        <div className="hidden lg:block">
          <TableOfContents content={activePost.content} variant="sidebar" title="글 목차 (Table of Contents)" />
        </div>
      )}

      {/* 0.1 Auto-Posting System Status Widget */}
      {onOpenAutoPoster && (
        <div className="bg-gradient-to-br from-slate-950 via-indigo-950 to-slate-900 text-white rounded-2xl p-5 border border-indigo-500/30 shadow-lg space-y-3.5">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-2.5">
              <div className="w-8 h-8 rounded-xl bg-indigo-500/20 border border-indigo-400/30 flex items-center justify-center text-indigo-300">
                <Bot className="w-4.5 h-4.5" />
              </div>
              <div>
                <h3 className="font-heading font-black text-sm text-white flex items-center gap-1.5">
                  1인칭 자동 포스팅 엔진
                </h3>
                <span className="text-[11px] text-emerald-300 font-bold flex items-center gap-1">
                  <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
                  3대 핵심 카테고리 자동 발행 가동 중
                </span>
              </div>
            </div>
          </div>

          <p className="text-xs text-slate-200 leading-relaxed bg-white/10 p-3 rounded-xl border border-white/10 font-normal">
            매일 직장·부동산·연금 3대 분야에서 11년차 박과장이 직접 겪은 팩트 기반 스토리텔링 글을 자동 생성 및 배포합니다.
          </p>

          <div className="flex items-center justify-between pt-1 border-t border-white/10">
            <span className="text-xs text-slate-300">
              자동 누적: <strong className="text-indigo-200 font-num text-sm">{autoGeneratedCount}</strong>편
            </span>
            <button
              type="button"
              onClick={onOpenAutoPoster}
              className="bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold px-3.5 py-1.5 rounded-xl transition flex items-center gap-1 shadow-sm cursor-pointer"
            >
              <span>스케줄 관리</span>
              <ChevronRight className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
      )}

      {/* 1. Author Profile & Mission Box */}
      <div className="bg-white rounded-2xl p-5 border border-slate-200 shadow-xs space-y-4">
        <div className="flex items-center space-x-3.5">
          <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-indigo-900 to-slate-900 text-white flex items-center justify-center font-bold shadow-xs shrink-0 text-xl">
            👨‍💼
          </div>
          <div>
            <div className="flex items-center gap-1.5">
              <h3 className="font-heading font-black text-slate-950 text-base">박과장 (11년차)</h3>
              <span className="bg-indigo-50 text-indigo-700 text-[10px] font-bold px-2 py-0.5 rounded-full border border-indigo-200">
                실전 경험자
              </span>
            </div>
            <p className="font-body text-xs text-slate-600 mt-0.5 font-medium">돈 지키는 생생 스토리텔러</p>
          </div>
        </div>

        <p className="font-body text-xs text-slate-700 leading-relaxed bg-slate-50 p-3 rounded-xl border border-slate-100 font-medium">
          "퇴직금 누락 380만원을 직접 찾아내고, 첫 집 매수 시 취득세 200만원을 깎아낸 실전 팩트만 1인칭으로 기록합니다. 가만히 있으면 아무도 내 돈을 지켜주지 않습니다."
        </p>

        <div className="pt-2 border-t border-slate-100 flex items-center justify-between text-xs text-slate-600">
          <span className="flex items-center gap-1 font-mono text-[11px] font-semibold text-slate-700">
            <Mail className="w-3.5 h-3.5 text-slate-500" />
            contact@park-money.kr
          </span>
          <button
            type="button"
            onClick={() => onSelectCategory('about')}
            className="text-indigo-600 hover:text-indigo-800 font-bold flex items-center gap-0.5 text-[11px] cursor-pointer"
          >
            <span>소개글 보기</span>
            <ChevronRight className="w-3 h-3" />
          </button>
        </div>
      </div>

      {/* 2. Top 5 Popular Real Stories */}
      <div className="bg-white rounded-2xl p-5 border border-slate-200 shadow-xs space-y-3.5">
        <div className="flex items-center justify-between border-b border-slate-100 pb-2.5">
          <h3 className="font-heading text-sm font-black text-slate-950 flex items-center gap-1.5">
            <TrendingUp className="w-4 h-4 text-indigo-600" />
            인기 실화 포스팅 TOP 5
          </h3>
          <span className="text-[11px] text-slate-500 font-medium">조회수 기준</span>
        </div>

        <div className="space-y-2.5">
          {popularPosts.map((post, idx) => (
            <div
              key={post.id}
              onClick={() => onSelectPost(post)}
              className="flex items-start gap-2.5 group cursor-pointer p-1.5 rounded-xl hover:bg-slate-50 transition"
            >
              <span className={`font-num font-black text-xs px-2 py-0.5 rounded-md shrink-0 ${
                idx === 0 ? 'bg-indigo-600 text-white' : idx === 1 ? 'bg-indigo-100 text-indigo-900 font-bold' : 'bg-slate-100 text-slate-800 font-bold'
              }`}>
                {idx + 1}
              </span>
              <div className="min-w-0">
                <p className="font-heading text-xs font-bold text-slate-900 group-hover:text-indigo-600 transition-colors line-clamp-2 leading-snug">
                  {post.title}
                </p>
                <div className="flex items-center gap-2 text-[11px] text-slate-500 mt-1 font-body font-medium">
                  <span>{post.categoryName}</span>
                  <span>·</span>
                  <span>조회 {post.viewCount.toLocaleString()}</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* 3. 3 Core Categories Breakdown */}
      <div className="bg-white rounded-2xl p-5 border border-slate-200 shadow-xs space-y-3">
        <h3 className="font-heading text-sm font-black text-slate-950 flex items-center gap-1.5 border-b border-slate-100 pb-2.5">
          <Folder className="w-4 h-4 text-emerald-600" />
          3대 핵심 카테고리
        </h3>

        <div className="space-y-1.5">
          {categories.map((cat) => (
            <button
              key={cat.id}
              type="button"
              onClick={() => onSelectCategory(cat.id)}
              className="w-full text-left p-2.5 rounded-xl text-xs hover:bg-slate-50 transition cursor-pointer text-slate-800 border border-slate-100 group"
            >
              <div className="flex items-center justify-between font-bold">
                <span className="flex items-center gap-2 group-hover:text-indigo-600 transition-colors">
                  <span>{cat.icon}</span>
                  <span>{cat.name}</span>
                </span>
                <span className="font-num text-[11px] bg-slate-100 text-slate-700 font-bold px-2 py-0.5 rounded-full">
                  {cat.count}편
                </span>
              </div>
              <p className="text-[11px] text-slate-500 mt-1 font-normal line-clamp-1">
                {cat.desc}
              </p>
            </button>
          ))}
        </div>
      </div>

      {/* 4. Useful Calculators Box */}
      <div className="bg-gradient-to-br from-indigo-50/70 to-blue-50/70 rounded-2xl p-5 border border-indigo-100 shadow-xs space-y-3">
        <h3 className="font-heading text-sm font-black text-indigo-950 flex items-center gap-1.5">
          <Calculator className="w-4 h-4 text-indigo-600" />
          박과장이 직접 만든 실전 계산기
        </h3>
        <p className="text-xs text-slate-600 leading-relaxed">
          글에 나온 계산식과 법정 기준을 내 숫자로 1초 만에 검증해보세요.
        </p>

        <div className="grid grid-cols-2 gap-2 pt-1">
          <button
            type="button"
            onClick={() => onNavigateToCalculator('wage_salary')}
            className="p-2.5 bg-white hover:bg-indigo-600 hover:text-white text-slate-800 rounded-xl border border-indigo-100 text-xs font-bold transition flex items-center justify-between cursor-pointer shadow-2xs group"
          >
            <span>💵 실수령액</span>
            <ChevronRight className="w-3.5 h-3.5 text-slate-400 group-hover:text-white" />
          </button>
          <button
            type="button"
            onClick={() => onNavigateToCalculator('wage_hourly')}
            className="p-2.5 bg-white hover:bg-indigo-600 hover:text-white text-slate-800 rounded-xl border border-indigo-100 text-xs font-bold transition flex items-center justify-between cursor-pointer shadow-2xs group"
          >
            <span>⏱ 퇴직금·수당</span>
            <ChevronRight className="w-3.5 h-3.5 text-slate-400 group-hover:text-white" />
          </button>
          <button
            type="button"
            onClick={() => onNavigateToCalculator('property_tax')}
            className="p-2.5 bg-white hover:bg-indigo-600 hover:text-white text-slate-800 rounded-xl border border-indigo-100 text-xs font-bold transition flex items-center justify-between cursor-pointer shadow-2xs group"
          >
            <span>🏠 취득세·복비</span>
            <ChevronRight className="w-3.5 h-3.5 text-slate-400 group-hover:text-white" />
          </button>
          <button
            type="button"
            onClick={() => onNavigateToCalculator('finance_loan')}
            className="p-2.5 bg-white hover:bg-indigo-600 hover:text-white text-slate-800 rounded-xl border border-indigo-100 text-xs font-bold transition flex items-center justify-between cursor-pointer shadow-2xs group"
          >
            <span>🏦 대출 이자</span>
            <ChevronRight className="w-3.5 h-3.5 text-slate-400 group-hover:text-white" />
          </button>
        </div>
      </div>
    </aside>
  );
}
