import { CalculatorSpec, Field } from './model';

const f = (key: string, label: string, unit: string, defaultValue: number | string, type: Field['type'] = 'number'): Field => ({ key, label, unit, defaultValue, type });

export const koreaEssentialCalculators: CalculatorSpec[] = [
  { id:'insurance_national_pension', name:'국민연금 부담액 계산기', category:'insurance', icon:'🛡️', mode:'pension', description:'월 보수에 기준소득 상·하한을 적용해 근로자와 사업주 부담액을 나눠 계산합니다.', formula:'적용 기준소득 × 부담률', note:'기준소득월액과 요율은 적용 시점에 따라 달라질 수 있습니다.', fields:[f('income','월 보수','원',3000000),f('employeeRate','근로자 부담률','%',4.75),f('employerRate','사업주 부담률','%',4.75),f('minIncome','하한 기준소득','원',410000),f('maxIncome','상한 기준소득','원',6590000)] },
  { id:'insurance_health_premium', name:'건강보험료 계산기', category:'insurance', icon:'🛡️', mode:'rateSplit', description:'월 보수와 건강보험료율로 근로자·사업주 부담액을 계산합니다.', formula:'월 보수 × 보험료율 ÷ 2', note:'장기요양보험료는 별도 계산하거나 함께 더해야 합니다.', fields:[f('base','월 보수','원',3000000),f('totalRate','건강보험료율','%',7.09)], meta:{totalLabel:'건강보험료 총액',employeeLabel:'근로자 부담액',employerLabel:'사업주 부담액'} },
  { id:'insurance_longterm_care', name:'장기요양보험료 계산기', category:'insurance', icon:'🛡️', mode:'rateAmount', description:'건강보험료 기준 장기요양보험료를 계산합니다.', formula:'건강보험료 × 장기요양보험료율', note:'장기요양보험료율은 고시 기준에 따라 바뀔 수 있습니다.', fields:[f('base','건강보험료','원',106350),f('rate','장기요양보험료율','%',12.95)], meta:{resultLabel:'장기요양보험료'} },
  { id:'insurance_employee_total', name:'근로자 4대보험 공제액 계산기', category:'insurance', icon:'🛡️', mode:'employeeInsuranceTotal', description:'월 보수 기준 국민연금·건강보험·장기요양·고용보험 공제액을 합산합니다.', formula:'각 보험별 근로자 부담액 합계', note:'과세·비과세 항목과 보수월액 산정 기준에 따라 달라질 수 있습니다.', fields:[f('income','월 보수','원',3000000),f('pensionRate','국민연금 근로자율','%',4.75),f('healthRate','건강보험 근로자율','%',3.545),f('careRate','장기요양보험료율','%',12.95),f('employmentRate','고용보험 근로자율','%',0.9)] },
  { id:'insurance_freelancer_33', name:'프리랜서 3.3% 실수령액 계산기', category:'insurance', icon:'🛡️', mode:'freelancerNet', description:'프리랜서 계약금액에서 3.3% 원천징수액과 실수령액을 계산합니다.', formula:'계약금액 - 소득세 - 지방소득세', note:'종합소득세 신고 결과에 따라 환급 또는 추가 납부가 생길 수 있습니다.', fields:[f('gross','계약 금액','원',1000000),f('incomeTax','소득세','%',3),f('localTax','지방소득세','%',0.3)] },

  { id:'wage_weekly_holiday_pay', name:'주휴수당 계산기', category:'wage', icon:'💼', mode:'weeklyHolidayPay', description:'시급과 주 근무시간으로 주휴수당 발생 여부와 예상 금액을 계산합니다.', formula:'시급 × 주휴 인정 시간', note:'통상 주 15시간 이상 등 요건을 충족해야 발생합니다.', fields:[f('hourly','시급','원',10320),f('weeklyHours','주 근무시간','시간',20),f('workDays','주 근무일수','일',5)] },
  { id:'wage_severance_pay', name:'퇴직금 계산기', category:'wage', icon:'💼', mode:'severancePay', description:'최근 3개월 임금과 계속근로일수로 예상 퇴직금을 계산합니다.', formula:'1일 평균임금 × 30일 × 계속근로일수 ÷ 365', note:'상여금, 연차수당, 제외 기간에 따라 실제 금액은 달라질 수 있습니다.', fields:[f('threeMonthWage','최근 3개월 임금 합계','원',9000000),f('threeMonthDays','최근 3개월 일수','일',92),f('serviceDays','계속근로일수','일',1095),f('annualBonus','연간 상여금','원',0)] },
  { id:'wage_hourly_monthly', name:'시급 월급 환산 계산기', category:'wage', icon:'💼', mode:'hourlyMonthly', description:'시급과 주 근무시간으로 월 환산 급여를 계산합니다.', formula:'시급 × 주 근무시간 × 4.345주', note:'주휴수당 포함 여부와 실제 근무일수에 따라 달라질 수 있습니다.', fields:[f('hourly','시급','원',10320),f('weeklyHours','주 근무시간','시간',40)] },
  { id:'wage_overtime_pay', name:'연장근로수당 계산기', category:'wage', icon:'💼', mode:'premiumPay', description:'통상시급과 연장근로시간으로 가산수당을 계산합니다.', formula:'통상시급 × 시간 × 가산배율', note:'근로기준법상 요건과 사업장 규모에 따라 적용 여부가 달라질 수 있습니다.', fields:[f('hourly','통상시급','원',12000),f('hours','연장근로시간','시간',10),f('multiplier','가산 배율','배',1.5)], meta:{resultLabel:'연장근로수당'} },
  { id:'wage_annual_leave_pay', name:'연차수당 계산기', category:'wage', icon:'💼', mode:'annualLeavePay', description:'통상시급과 1일 소정근로시간, 미사용 연차일수로 연차수당을 계산합니다.', formula:'통상시급 × 1일 근로시간 × 미사용 연차일수', note:'연차 발생일수와 사용촉진 여부에 따라 지급 여부가 달라질 수 있습니다.', fields:[f('hourly','통상시급','원',12000),f('dailyHours','1일 근로시간','시간',8),f('days','미사용 연차','일',5)] },

  { id:'life_korean_age', name:'만 나이 계산기', category:'life', icon:'🧭', mode:'koreanAge', description:'생년월일과 기준일을 넣어 만 나이를 계산합니다.', formula:'기준일의 생일 경과 여부 반영', note:'서비스별로 별도 나이 기준을 둘 수 있습니다.', fields:[f('birth','생년월일','','1990-01-01','date'),f('base','기준일','','2026-06-20','date')] },
  { id:'life_date_diff', name:'날짜 차이 계산기', category:'life', icon:'🧭', mode:'dateDiff', description:'두 날짜 사이의 일수와 주 단위 차이를 계산합니다.', formula:'종료일 - 시작일', note:'계약기간 계산 시 초일 산입 여부는 별도 기준을 확인해야 합니다.', fields:[f('start','시작일','','2026-01-01','date'),f('end','종료일','','2026-06-20','date')] },
  { id:'life_dday', name:'디데이 계산기', category:'life', icon:'🧭', mode:'dday', description:'기준일에서 목표일까지 남은 날짜를 계산합니다.', formula:'목표일 - 기준일', note:'행사·시험·납부일 관리용으로 사용할 수 있습니다.', fields:[f('base','기준일','','2026-06-20','date'),f('target','목표일','','2026-12-31','date')] },
  { id:'life_electric_bill', name:'전기요금 계산기', category:'life', icon:'🧭', mode:'utilityBill', description:'사용량, 단가, 기본요금, 부가세로 월 전기요금을 추정합니다.', formula:'기본요금 + 사용량 × 단가 + 부가세', note:'실제 전기요금은 누진제와 조정액이 반영될 수 있습니다.', fields:[f('usage','사용량','kWh',250),f('unitPrice','kWh 단가','원',120),f('baseFee','기본요금','원',1600),f('vatRate','부가세율','%',10)] },
  { id:'life_split_bill', name:'공동생활비 나누기 계산기', category:'life', icon:'🧭', mode:'splitCost', description:'총 생활비를 인원수로 나누어 1인 부담액을 계산합니다.', formula:'총 비용 ÷ 인원수', note:'개인별 사용량이 다르면 가중치를 따로 적용해야 합니다.', fields:[f('total','총 생활비','원',480000),f('people','인원수','명',3)] },

  { id:'finance_loan_payment', name:'대출 원리금 상환 계산기', category:'finance', icon:'💰', mode:'loanPayment', description:'대출 원금, 금리, 기간으로 매월 원리금 균등 상환액을 계산합니다.', formula:'원리금균등 상환 공식', note:'거치기간과 중도상환수수료는 별도 확인이 필요합니다.', fields:[f('principal','대출 원금','원',50000000),f('rate','연 이율','%',4.5),f('months','상환 기간','개월',120)] },
  { id:'finance_interest_only', name:'대출 이자만 계산기', category:'finance', icon:'💰', mode:'monthlyInterest', description:'대출 원금과 연 이율로 월 이자 부담액을 계산합니다.', formula:'대출원금 × 연이율 ÷ 12', note:'원금상환액과 수수료는 포함하지 않습니다.', fields:[f('principal','대출 원금','원',50000000),f('rate','연 이율','%',4.5)] },
  { id:'finance_simple_interest', name:'예금 단리 이자 계산기', category:'finance', icon:'💰', mode:'simpleInterest', description:'원금, 금리, 기간으로 단리 이자를 계산합니다.', formula:'원금 × 연이율 × 기간', note:'이자소득세를 제외한 세후 금액은 별도 계산해야 합니다.', fields:[f('principal','예치 원금','원',10000000),f('rate','연 이율','%',3.5),f('months','예치 기간','개월',12)] },
  { id:'finance_dsr', name:'DSR 계산기', category:'finance', icon:'💰', mode:'dsr', description:'연 소득 대비 연간 원리금 상환액 비율을 계산합니다.', formula:'연간 원리금 상환액 ÷ 연소득 × 100', note:'금융기관 심사는 대출 종류와 규제 기준에 따라 달라집니다.', fields:[f('annualIncome','연 소득','원',50000000),f('annualDebtPayment','연간 원리금 상환액','원',12000000),f('otherDebtPayment','기타 대출 연상환액','원',3000000)] },
  { id:'finance_monthly_savings', name:'적금 만기금액 계산기', category:'finance', icon:'💰', mode:'monthlySavings', description:'월 납입액과 금리, 기간으로 적금 만기금액을 추정합니다.', formula:'월 납입액의 미래가치 합산', note:'은행별 이자 계산 방식과 세금 적용에 따라 달라질 수 있습니다.', fields:[f('monthly','월 납입액','원',300000),f('rate','연 이율','%',4),f('months','납입 기간','개월',12)] },

  { id:'property_acquisition_tax', name:'취득세 계산기', category:'property', icon:'🏠', mode:'acquisitionTax', description:'취득가액과 세율을 넣어 취득세 예상액을 계산합니다.', formula:'취득가액 × 적용 세율', note:'주택 수, 지역, 면적, 취득 원인에 따라 세율이 달라질 수 있습니다.', fields:[f('price','취득가액','원',500000000),f('taxRate','취득세율','%',1.1),f('extraRate','농특세·교육세율','%',0.2)] },
  { id:'property_price_per_pyeong', name:'평당가 계산기', category:'property', icon:'🏠', mode:'pricePerPyeong', description:'거래금액과 면적으로 평당 가격을 계산합니다.', formula:'거래금액 ÷ 평수', note:'비교 시 전용면적 기준인지 공급면적 기준인지 통일해야 합니다.', fields:[f('price','거래금액','원',600000000),f('area','면적','평',30)] },
  { id:'property_brokerage_fee', name:'부동산 중개보수 계산기', category:'property', icon:'🏠', mode:'rateAmount', description:'거래금액에 중개보수율을 적용해 예상 중개보수를 계산합니다.', formula:'거래금액 × 중개보수율', note:'주택·오피스텔·상가, 매매·임대차에 따라 상한요율이 달라집니다.', fields:[f('base','거래금액','원',500000000),f('rate','중개보수율','%',0.4)], meta:{resultLabel:'예상 중개보수'} },
  { id:'property_ltv', name:'LTV 계산기', category:'property', icon:'🏠', mode:'ltv', description:'주택가격 대비 대출금 비율을 계산합니다.', formula:'대출금액 ÷ 주택가격 × 100', note:'지역·주택 수·차주 조건에 따라 적용 가능한 LTV 한도가 달라집니다.', fields:[f('loan','대출금액','원',300000000),f('price','주택가격','원',600000000)] },
  { id:'property_rent_conversion', name:'전월세 전환 계산기', category:'property', icon:'🏠', mode:'rentConversion', description:'보증금 차액과 전환율로 월세 전환액을 계산합니다.', formula:'보증금 차액 × 전환율 ÷ 12', note:'법정 전월세전환율과 실제 시장 전환율은 다를 수 있습니다.', fields:[f('depositDiff','보증금 차액','원',50000000),f('rate','전환율','%',5.5)] },

  { id:'health_bmi', name:'BMI 계산기', category:'health', icon:'🏃', mode:'bmi', description:'키와 몸무게로 체질량지수와 판정 구간을 계산합니다.', formula:'몸무게 ÷ 키(m)^2', note:'BMI는 체성분을 직접 측정하지 않으므로 참고 지표로만 사용하세요.', fields:[f('height','키','cm',170),f('weight','몸무게','kg',68)] },
  { id:'health_bmr', name:'기초대사량 계산기', category:'health', icon:'🏃', mode:'bmr', description:'키, 몸무게, 나이, 성별 보정값으로 기초대사량을 추정합니다.', formula:'10×체중 + 6.25×키 - 5×나이 + 보정값', note:'근육량과 활동량에 따라 실제 필요 열량은 달라집니다.', fields:[f('weight','몸무게','kg',68),f('height','키','cm',170),f('age','나이','세',35),f('genderOffset','성별 보정값 남성 5 / 여성 -161','',5)] },
  { id:'health_water', name:'하루 물 섭취량 계산기', category:'health', icon:'🏃', mode:'waterIntake', description:'체중 기준 하루 권장 수분 섭취량을 계산합니다.', formula:'체중 × kg당 권장량', note:'질환, 운동량, 날씨에 따라 적정량은 달라질 수 있습니다.', fields:[f('weight','몸무게','kg',68),f('mlPerKg','kg당 권장량','mL',35)] },
  { id:'health_running_pace', name:'러닝 페이스 계산기', category:'health', icon:'🏃', mode:'runningPace', description:'거리와 소요시간으로 km당 페이스와 평균속도를 계산합니다.', formula:'총 시간 ÷ 거리', note:'GPS 오차와 코스 고도에 따라 실제 페이스는 달라질 수 있습니다.', fields:[f('distance','거리','km',5),f('minutes','분','분',30),f('seconds','초','초',0)] },
  { id:'health_protein', name:'단백질 섭취량 계산기', category:'health', icon:'🏃', mode:'proteinIntake', description:'체중과 kg당 섭취 기준으로 하루 단백질 목표량을 계산합니다.', formula:'체중 × kg당 단백질', note:'신장 질환 등이 있으면 섭취량을 임의로 늘리지 마세요.', fields:[f('weight','몸무게','kg',68),f('gramPerKg','kg당 단백질','g',1.6)] },

  { id:'auto_fuel_cost', name:'주유비 계산기', category:'auto', icon:'🚗', mode:'fuelCost', description:'주행거리, 연비, 유가로 예상 주유비를 계산합니다.', formula:'거리 ÷ 연비 × 유가', note:'실연비는 운전습관과 도로상황에 따라 달라집니다.', fields:[f('distance','주행거리','km',120),f('efficiency','연비','km/L',12),f('fuelPrice','유가','원/L',1650)] },
  { id:'auto_parking_fee', name:'주차요금 계산기', category:'auto', icon:'🚗', mode:'parkingFee', description:'기본시간 이후 단위요금을 적용해 주차비를 계산합니다.', formula:'기본요금 + 추가단위 × 단위요금', note:'일 최대요금과 할인권은 별도 적용해야 합니다.', fields:[f('totalMinutes','총 주차시간','분',145),f('baseMinutes','기본시간','분',30),f('baseFee','기본요금','원',1000),f('unitMinutes','추가 단위시간','분',10),f('unitFee','단위요금','원',500)] },
  { id:'auto_car_loan', name:'자동차 할부 계산기', category:'auto', icon:'🚗', mode:'loanPayment', description:'차량 할부원금, 금리, 기간으로 월 납입액을 계산합니다.', formula:'원리금균등 상환 공식', note:'선수금, 취득세, 보험료, 수수료는 별도 확인하세요.', fields:[f('principal','할부원금','원',25000000),f('rate','연 이율','%',6.5),f('months','할부기간','개월',60)] },
  { id:'auto_commute_cost', name:'출퇴근 교통비 계산기', category:'auto', icon:'🚗', mode:'commuteCost', description:'하루 왕복 교통비와 출근일수로 월 교통비를 계산합니다.', formula:'하루 교통비 × 월 출근일수', note:'정기권이나 환승 할인은 별도 반영하세요.', fields:[f('daily','하루 왕복 교통비','원',3200),f('days','월 출근일수','일',22)] },
  { id:'auto_average_speed', name:'평균속도 계산기', category:'auto', icon:'🚗', mode:'speed', description:'거리와 소요시간으로 평균속도를 계산합니다.', formula:'거리 ÷ 시간', note:'휴게시간을 포함할지 제외할지 기준을 통일하세요.', fields:[f('distance','거리','km',120),f('minutes','소요시간','분',100)] },

  { id:'education_average_score', name:'평균 점수 계산기', category:'education', icon:'📚', mode:'averageScore', description:'세 과목 점수의 평균을 계산합니다.', formula:'점수 합계 ÷ 과목 수', note:'가중치가 있는 과목은 가중평균 기준을 별도 적용해야 합니다.', fields:[f('score1','1과목 점수','점',85),f('score2','2과목 점수','점',90),f('score3','3과목 점수','점',78)] },
  { id:'education_gpa', name:'학점 GPA 계산기', category:'education', icon:'📚', mode:'gpa', description:'과목별 평점과 학점으로 GPA를 계산합니다.', formula:'평점×학점 합계 ÷ 학점 합계', note:'학교별 평점 만점과 환산 기준이 다를 수 있습니다.', fields:[f('grade1','1과목 평점','점',4.0),f('credit1','1과목 학점','학점',3),f('grade2','2과목 평점','점',3.5),f('credit2','2과목 학점','학점',3)] },
  { id:'education_attendance', name:'출석률 계산기', category:'education', icon:'📚', mode:'attendanceRate', description:'총 수업일과 출석일로 출석률을 계산합니다.', formula:'출석일 ÷ 총 수업일 × 100', note:'지각·조퇴·결석 처리 기준은 학교마다 다릅니다.', fields:[f('attended','출석일','일',85),f('total','총 수업일','일',95)] },
  { id:'education_final_needed', name:'기말고사 필요점수 계산기', category:'education', icon:'📚', mode:'finalScoreNeeded', description:'목표 평균을 맞추기 위해 기말에서 필요한 점수를 계산합니다.', formula:'(목표점수 - 현재점수×현재비중) ÷ 기말비중', note:'수행평가와 가산점이 있으면 별도 반영해야 합니다.', fields:[f('target','목표 최종점수','점',90),f('current','현재 점수','점',85),f('currentWeight','현재 반영비율','%',60),f('finalWeight','기말 반영비율','%',40)] },
  { id:'education_study_hours', name:'공부시간 계획 계산기', category:'education', icon:'📚', mode:'studyPlan', description:'목표 공부시간을 남은 날짜로 나누어 하루 공부량을 계산합니다.', formula:'총 목표시간 ÷ 남은 일수', note:'복습일과 예비일을 따로 빼두면 계획 달성률이 높아집니다.', fields:[f('totalHours','목표 공부시간','시간',120),f('days','남은 일수','일',30)] },

  { id:'business_break_even', name:'손익분기점 계산기', category:'business', icon:'📈', mode:'breakEven', description:'고정비와 개당 공헌이익으로 손익분기 판매량을 계산합니다.', formula:'고정비 ÷ (판매가 - 변동비)', note:'광고비, 수수료, 반품비를 변동비에 포함하면 더 현실적입니다.', fields:[f('fixedCost','월 고정비','원',3000000),f('price','판매가','원',30000),f('variableCost','개당 변동비','원',12000)] },
  { id:'business_margin_rate', name:'마진율 계산기', category:'business', icon:'📈', mode:'marginRate', description:'판매가에서 원가와 수수료를 빼 순마진과 마진율을 계산합니다.', formula:'(판매가 - 원가 - 수수료) ÷ 판매가', note:'부가세 포함가와 공급가를 구분해야 합니다.', fields:[f('price','판매가','원',30000),f('cost','원가','원',12000),f('fee','수수료','원',3000)] },
  { id:'business_vat', name:'부가세 계산기', category:'business', icon:'📈', mode:'vat', description:'공급가액 기준 부가세와 합계금액을 계산합니다.', formula:'공급가액 × 부가세율', note:'면세·간이과세·영세율 여부에 따라 실제 신고액은 달라집니다.', fields:[f('supply','공급가액','원',1000000),f('vatRate','부가세율','%',10)] },
  { id:'business_roas', name:'ROAS 계산기', category:'business', icon:'📈', mode:'roas', description:'광고비 대비 매출 효율을 계산합니다.', formula:'광고매출 ÷ 광고비 × 100', note:'ROAS가 높아도 마진율이 낮으면 손실일 수 있습니다.', fields:[f('revenue','광고 매출','원',5000000),f('adCost','광고비','원',1000000)] },
  { id:'business_conversion_rate', name:'전환율 계산기', category:'business', icon:'📈', mode:'conversionRate', description:'방문자 수 대비 구매·문의 전환율을 계산합니다.', formula:'전환 수 ÷ 방문자 수 × 100', note:'유입 채널별로 나누어 봐야 개선 지점을 찾기 쉽습니다.', fields:[f('conversions','전환 수','건',45),f('visitors','방문자 수','명',1500)] },

  { id:'shopping_discount_price', name:'할인가 계산기', category:'shopping', icon:'🛒', mode:'discountPrice', description:'정가와 할인율로 할인금액과 최종가를 계산합니다.', formula:'정가 × (1 - 할인율)', note:'쿠폰과 포인트 적용 순서에 따라 실제 결제금액이 달라질 수 있습니다.', fields:[f('price','정가','원',100000),f('discountRate','할인율','%',20)] },
  { id:'shopping_bundle_unit', name:'묶음상품 단가 계산기', category:'shopping', icon:'🛒', mode:'bundleUnitPrice', description:'총 결제액과 수량으로 개당 단가를 계산합니다.', formula:'(상품금액 + 배송비) ÷ 수량', note:'용량이 다른 상품은 g당·mL당 단가로 비교하세요.', fields:[f('total','상품금액','원',30000),f('shipping','배송비','원',3000),f('quantity','수량','개',6)] },
  { id:'shopping_point_discount', name:'포인트 사용 후 결제액 계산기', category:'shopping', icon:'🛒', mode:'pointDiscount', description:'상품금액에서 포인트와 쿠폰을 뺀 최종 결제액을 계산합니다.', formula:'상품금액 - 포인트 - 쿠폰', note:'최소 결제금액 조건과 적립 제외 조건을 확인하세요.', fields:[f('price','상품금액','원',80000),f('point','사용 포인트','원',5000),f('coupon','쿠폰금액','원',7000)] },
  { id:'shopping_free_shipping_gap', name:'무료배송 추가금액 계산기', category:'shopping', icon:'🛒', mode:'freeShippingGap', description:'무료배송 기준까지 추가로 필요한 금액을 계산합니다.', formula:'무료배송 기준 - 현재 장바구니 금액', note:'불필요한 추가구매보다 배송비가 더 싼지 비교하세요.', fields:[f('threshold','무료배송 기준','원',50000),f('cart','현재 장바구니','원',38000)] },
  { id:'shopping_unit_compare', name:'단위가격 비교 계산기', category:'shopping', icon:'🛒', mode:'unitCompare', description:'가격과 용량으로 단위당 가격을 계산합니다.', formula:'가격 ÷ 용량', note:'동일 단위로 환산한 뒤 비교해야 정확합니다.', fields:[f('price','가격','원',12900),f('amount','용량','g',500)] },

  { id:'unit_cm_inch', name:'cm 인치 변환기', category:'unit', icon:'📐', mode:'cmToInch', description:'센티미터를 인치로 변환합니다.', formula:'cm ÷ 2.54', note:'모니터·가구·의류 사이즈 확인에 사용할 수 있습니다.', fields:[f('cm','센티미터','cm',30)] },
  { id:'unit_kg_lb', name:'kg 파운드 변환기', category:'unit', icon:'📐', mode:'kgToLb', description:'킬로그램을 파운드로 변환합니다.', formula:'kg × 2.20462', note:'해외 직구 상품 무게 확인에 사용할 수 있습니다.', fields:[f('kg','킬로그램','kg',10)] },
  { id:'unit_pyeong_m2', name:'평 제곱미터 변환기', category:'unit', icon:'📐', mode:'pyeongToM2', description:'평수를 제곱미터로 변환합니다.', formula:'평 × 3.305785', note:'부동산 면적 비교 시 전용·공급면적을 구분하세요.', fields:[f('pyeong','평수','평',30)] },
  { id:'unit_m2_pyeong', name:'제곱미터 평 변환기', category:'unit', icon:'📐', mode:'m2ToPyeong', description:'제곱미터를 평수로 변환합니다.', formula:'㎡ ÷ 3.305785', note:'계약서의 면적 단위를 확인할 때 사용하세요.', fields:[f('m2','제곱미터','㎡',84)] },
  { id:'unit_celsius_fahrenheit', name:'섭씨 화씨 변환기', category:'unit', icon:'📐', mode:'celsiusFahrenheit', description:'섭씨 온도를 화씨로 변환합니다.', formula:'℃ × 9 ÷ 5 + 32', note:'해외 날씨 정보를 볼 때 유용합니다.', fields:[f('celsius','섭씨','℃',25)] },

  { id:'travel_budget', name:'여행경비 계산기', category:'travel', icon:'✈️', mode:'travelBudget', description:'교통·숙박·식비·기타비용을 합산해 총 여행경비와 1인 경비를 계산합니다.', formula:'총 비용 ÷ 인원수', note:'환전수수료와 여행자보험은 별도 항목으로 추가하세요.', fields:[f('transport','교통비','원',300000),f('lodging','숙박비','원',500000),f('food','식비','원',250000),f('extra','기타비용','원',150000),f('people','인원수','명',2)] },
  { id:'travel_timezone', name:'시차 계산기', category:'travel', icon:'✈️', mode:'timeZone', description:'현재 시각과 시차를 입력해 도착지 현지시각을 계산합니다.', formula:'현재시각 + 시차', note:'서머타임 적용 여부는 별도 확인하세요.', fields:[f('hour','현재 시각','시',14),f('minute','분','분',30),f('offset','시차','시간',1)] },
  { id:'travel_exchange', name:'환전 계산기', category:'travel', icon:'✈️', mode:'exchange', description:'원화 금액과 환율로 외화 환산액을 계산합니다.', formula:'원화 ÷ 환율', note:'실제 환전은 우대율과 수수료가 적용됩니다.', fields:[f('krw','원화 금액','원',1000000),f('rate','환율','원',1350)] },
  { id:'travel_route_time', name:'이동시간 계산기', category:'travel', icon:'✈️', mode:'routeTime', description:'거리와 평균속도로 예상 이동시간을 계산합니다.', formula:'거리 ÷ 평균속도', note:'휴게시간, 입국심사, 환승 대기시간은 별도 추가하세요.', fields:[f('distance','이동거리','km',240),f('speed','평균속도','km/h',80)] },
  { id:'travel_dday', name:'여행 출발 D-day 계산기', category:'travel', icon:'✈️', mode:'dday', description:'기준일에서 여행 출발일까지 남은 날짜를 계산합니다.', formula:'출발일 - 기준일', note:'여권·비자·환전 준비 일정을 함께 체크하세요.', fields:[f('base','기준일','','2026-06-20','date'),f('target','출발일','','2026-08-01','date')] },
];
