import { CalculatorSpec, Field } from './model';

const f = (key: string, label: string, unit: string, defaultValue: number | string, type: Field['type'] = 'number'): Field => ({ key, label, unit, defaultValue, type });

export const koreaExpansionCalculators: CalculatorSpec[] = [
  { id:'insurance_employment_premium', name:'고용보험료 계산기', category:'insurance', icon:'🛡️', mode:'rateSplit', description:'월 보수와 고용보험료율을 기준으로 근로자와 사업주 부담액을 계산합니다.', formula:'월 보수 × 고용보험료율 ÷ 2', note:'사업장 업종과 고용안정·직업능력개발사업 요율은 별도 적용될 수 있습니다.', fields:[f('base','월 보수','원',3000000),f('totalRate','고용보험료율','%',1.8)], meta:{totalLabel:'고용보험료 총액',employeeLabel:'근로자 부담액',employerLabel:'사업주 부담액'} },
  { id:'insurance_industrial_accident', name:'산재보험료 계산기', category:'insurance', icon:'🛡️', mode:'rateAmount', description:'보수총액과 산재보험료율로 사업주 부담 산재보험료를 계산합니다.', formula:'보수총액 × 산재보험료율', note:'산재보험료율은 업종별로 크게 다르므로 실제 업종 요율을 확인해야 합니다.', fields:[f('base','보수총액','원',3000000),f('rate','산재보험료율','%',1.0)], meta:{resultLabel:'예상 산재보험료'} },
  { id:'insurance_company_cost', name:'회사 4대보험 부담액 계산기', category:'insurance', icon:'🛡️', mode:'rateAmount', description:'월 보수에 회사 부담 보험료율을 적용해 회사 측 인건비 부담액을 계산합니다.', formula:'월 보수 × 회사부담 보험료율', note:'국민연금, 건강보험, 고용보험, 산재보험 요율을 합산해 입력하세요.', fields:[f('base','월 보수','원',3000000),f('rate','회사부담 합산요율','%',10.5)], meta:{resultLabel:'회사 부담 보험료'} },
  { id:'insurance_durunuri_support', name:'두루누리 지원금 계산기', category:'insurance', icon:'🛡️', mode:'rateAmount', description:'보험료 총액과 지원율을 입력해 예상 지원금을 계산합니다.', formula:'보험료 총액 × 지원율', note:'지원 대상, 근로자 수, 보수 기준 등 실제 요건을 반드시 확인해야 합니다.', fields:[f('base','보험료 총액','원',180000),f('rate','지원율','%',80)], meta:{resultLabel:'예상 지원금'} },
  { id:'insurance_annual_budget', name:'연간 보험료 예산 계산기', category:'insurance', icon:'🛡️', mode:'monthlyToAnnual', description:'월 보험료를 기준으로 연간 보험료 예산을 계산합니다.', formula:'월 보험료 × 12개월', note:'중도 입사·퇴사, 보수 변경, 정산 보험료는 별도 반영해야 합니다.', fields:[f('monthly','월 보험료 합계','원',320000)] },

  { id:'wage_night_pay', name:'야간근로수당 계산기', category:'wage', icon:'💼', mode:'premiumPay', description:'통상시급과 야간근로시간, 가산배율로 야간근로수당을 계산합니다.', formula:'통상시급 × 야간근로시간 × 가산배율', note:'야간근로 시간대와 가산 적용 요건은 근로기준법과 근로계약을 확인하세요.', fields:[f('hourly','통상시급','원',12000),f('hours','야간근로시간','시간',8),f('multiplier','가산 배율','배',1.5)], meta:{resultLabel:'야간근로수당'} },
  { id:'wage_holiday_pay', name:'휴일근로수당 계산기', category:'wage', icon:'💼', mode:'premiumPay', description:'통상시급과 휴일근로시간으로 예상 휴일근로수당을 계산합니다.', formula:'통상시급 × 휴일근로시간 × 가산배율', note:'8시간 초과 여부와 사업장 규모에 따라 가산 기준이 달라질 수 있습니다.', fields:[f('hourly','통상시급','원',12000),f('hours','휴일근로시간','시간',8),f('multiplier','가산 배율','배',1.5)], meta:{resultLabel:'휴일근로수당'} },
  { id:'wage_daily_pay', name:'일급 계산기', category:'wage', icon:'💼', mode:'premiumPay', description:'시급과 하루 근무시간으로 일급을 계산합니다.', formula:'시급 × 하루 근무시간', note:'주휴수당, 연장수당, 세금 공제는 별도 계산해야 합니다.', fields:[f('hourly','시급','원',10320),f('hours','하루 근무시간','시간',8),f('multiplier','배율','배',1)], meta:{resultLabel:'일급'} },
  { id:'wage_net_monthly', name:'월급 실수령액 간편 계산기', category:'wage', icon:'💼', mode:'netPayByDeduction', description:'월급에서 예상 공제율을 적용해 간편 실수령액을 계산합니다.', formula:'월급 - 월급 × 공제율', note:'정확한 실수령액은 비과세, 부양가족, 4대보험, 소득세 조건에 따라 달라집니다.', fields:[f('gross','세전 월급','원',3000000),f('deductionRate','예상 공제율','%',9.5)] },
  { id:'wage_bonus_net', name:'상여금 실수령액 계산기', category:'wage', icon:'💼', mode:'netPayByDeduction', description:'상여금에서 예상 공제율을 빼고 실수령액을 계산합니다.', formula:'상여금 - 상여금 × 공제율', note:'상여금은 지급 방식과 세율 적용 방식에 따라 실제 공제액이 달라질 수 있습니다.', fields:[f('gross','세전 상여금','원',1000000),f('deductionRate','예상 공제율','%',15)] },

  { id:'life_gas_bill', name:'가스요금 계산기', category:'life', icon:'🧭', mode:'utilityBill', description:'가스 사용량, 단가, 기본요금, 부가세로 예상 가스요금을 계산합니다.', formula:'기본요금 + 사용량 × 단가 + 부가세', note:'계절별 단가와 지역 도시가스사 기준에 따라 실제 금액은 달라질 수 있습니다.', fields:[f('usage','사용량','㎥',80),f('unitPrice','단가','원',950),f('baseFee','기본요금','원',1200),f('vatRate','부가세율','%',10)] },
  { id:'life_water_bill', name:'수도요금 계산기', category:'life', icon:'🧭', mode:'utilityBill', description:'수도 사용량과 단가를 기준으로 예상 수도요금을 계산합니다.', formula:'기본요금 + 사용량 × 단가 + 부가세', note:'상하수도, 물이용부담금, 지역별 누진제가 별도 적용될 수 있습니다.', fields:[f('usage','사용량','㎥',20),f('unitPrice','㎥ 단가','원',850),f('baseFee','기본요금','원',1000),f('vatRate','부가세율','%',0)] },
  { id:'life_subscription_split', name:'구독료 나누기 계산기', category:'life', icon:'🧭', mode:'splitCost', description:'월 구독료를 함께 사용하는 인원수로 나누어 1인 부담액을 계산합니다.', formula:'월 구독료 ÷ 인원수', note:'계정 공유 정책과 결제자 부담 수수료를 함께 확인하세요.', fields:[f('total','월 구독료','원',17000),f('people','사용 인원','명',4)] },
  { id:'life_heating_split', name:'냉난방비 분담 계산기', category:'life', icon:'🧭', mode:'splitCost', description:'냉난방비 총액을 인원수나 세대수로 나누어 부담액을 계산합니다.', formula:'냉난방비 총액 ÷ 분담 인원', note:'면적이나 사용량이 다르면 단순 균등분담보다 가중분담이 적합할 수 있습니다.', fields:[f('total','냉난방비 총액','원',240000),f('people','분담 인원','명',3)] },
  { id:'life_saving_rate', name:'가계 저축률 계산기', category:'life', icon:'🧭', mode:'percentageOf', description:'월소득 중 저축액이 차지하는 비율을 계산합니다.', formula:'월 저축액 ÷ 월 소득 × 100', note:'비상금, 투자금, 대출상환액을 저축으로 볼지 기준을 통일하세요.', fields:[f('part','월 저축액','원',800000),f('total','월 소득','원',3500000)], meta:{resultLabel:'저축률'} },

  { id:'finance_compound_interest', name:'복리 이자 계산기', category:'finance', icon:'💰', mode:'compoundInterest', description:'원금, 연이율, 기간을 기준으로 복리 만기금액을 계산합니다.', formula:'원금 × (1 + 월이율)^개월수', note:'세금, 중도해지, 우대금리 조건은 별도 반영해야 합니다.', fields:[f('principal','원금','원',10000000),f('rate','연 이율','%',4),f('months','기간','개월',24)] },
  { id:'finance_card_installment', name:'카드 할부 월납입 계산기', category:'finance', icon:'💰', mode:'divideAmount', description:'결제금액을 할부 개월수로 나누어 월 납입액을 계산합니다.', formula:'결제금액 ÷ 할부개월수', note:'유이자 할부는 카드사 수수료가 별도로 붙을 수 있습니다.', fields:[f('total','결제금액','원',1200000),f('count','할부개월수','개월',6)], meta:{resultLabel:'월 납입액'} },
  { id:'finance_stock_return', name:'주식 수익률 계산기', category:'finance', icon:'💰', mode:'returnRate', description:'매수가와 매도가, 수량으로 투자손익과 수익률을 계산합니다.', formula:'(매도가 - 매수가) × 수량', note:'거래세와 수수료는 별도 반영해야 실제 손익에 가깝습니다.', fields:[f('buy','매수가','원',10000),f('sell','매도가','원',11200),f('quantity','수량','주',100)] },
  { id:'finance_target_saving', name:'목표금액 월저축 계산기', category:'finance', icon:'💰', mode:'targetMonthlySaving', description:'목표금액과 현재금액, 남은 기간으로 필요한 월 저축액을 계산합니다.', formula:'(목표금액 - 현재금액) ÷ 남은 개월수', note:'이자와 투자수익을 제외한 단순 저축 기준입니다.', fields:[f('target','목표금액','원',20000000),f('current','현재금액','원',5000000),f('months','남은 기간','개월',24)] },
  { id:'finance_exchange_krw', name:'환율 환산 계산기', category:'finance', icon:'💰', mode:'exchange', description:'원화 금액과 환율을 입력해 외화 환산액을 계산합니다.', formula:'원화 ÷ 환율', note:'은행별 우대율, 환전수수료, 송금수수료는 별도 적용될 수 있습니다.', fields:[f('krw','원화 금액','원',1000000),f('rate','환율','원',1350)] },

  { id:'property_jeonse_ratio', name:'전세가율 계산기', category:'property', icon:'🏠', mode:'percentageOf', description:'주택가격 대비 전세보증금 비율을 계산합니다.', formula:'전세보증금 ÷ 주택가격 × 100', note:'전세가율이 높을수록 보증금 회수 리스크를 더 꼼꼼히 봐야 합니다.', fields:[f('part','전세보증금','원',400000000),f('total','주택가격','원',600000000)], meta:{resultLabel:'전세가율'} },
  { id:'property_monthly_rent_yield', name:'월세 수익률 계산기', category:'property', icon:'🏠', mode:'rentalYield', description:'보증금과 월세를 기준으로 연 임대수익률을 계산합니다.', formula:'월세 × 12 ÷ 투자금액 × 100', note:'공실, 수선비, 세금, 대출이자는 별도로 차감해야 합니다.', fields:[f('monthlyRent','월세','원',800000),f('investment','투자금액','원',300000000)] },
  { id:'property_maintenance_split', name:'관리비 분담 계산기', category:'property', icon:'🏠', mode:'splitCost', description:'공동 관리비를 인원수나 세대수로 나누어 분담액을 계산합니다.', formula:'관리비 총액 ÷ 분담 수', note:'면적별 부과 항목은 균등분담이 아니라 면적 기준이 필요할 수 있습니다.', fields:[f('total','관리비 총액','원',180000),f('people','분담 수','명/세대',3)] },
  { id:'property_interior_unit_price', name:'인테리어 평당 비용 계산기', category:'property', icon:'🏠', mode:'pricePerPyeong', description:'총 인테리어 비용을 면적으로 나누어 평당 비용을 계산합니다.', formula:'총 비용 ÷ 평수', note:'자재, 철거, 전기, 설비, 가구 포함 여부를 구분해야 합니다.', fields:[f('price','총 비용','원',30000000),f('area','면적','평',24)] },
  { id:'property_capital_gain', name:'양도차익 계산기', category:'property', icon:'🏠', mode:'capitalGain', description:'매도가에서 취득가와 필요경비를 빼 양도차익을 계산합니다.', formula:'매도가 - 취득가 - 필요경비', note:'양도소득세는 보유기간, 주택 수, 공제 조건에 따라 별도 계산해야 합니다.', fields:[f('sell','매도가','원',700000000),f('buy','취득가','원',500000000),f('expense','필요경비','원',20000000)] },

  { id:'health_weight_goal_days', name:'목표 체중 감량 기간 계산기', category:'health', icon:'🏃', mode:'weightGoalDays', description:'감량 목표와 주당 감량 속도를 기준으로 예상 기간을 계산합니다.', formula:'감량 목표 ÷ 주당 감량량', note:'무리한 감량은 건강에 부담이 될 수 있으므로 참고용으로만 사용하세요.', fields:[f('current','현재 체중','kg',78),f('target','목표 체중','kg',70),f('weeklyLoss','주당 감량 목표','kg',0.5)] },
  { id:'health_exercise_calorie', name:'운동 칼로리 소모 계산기', category:'health', icon:'🏃', mode:'calorieBurn', description:'운동시간과 시간당 소모 칼로리로 총 소모량을 계산합니다.', formula:'운동시간 × 시간당 소모 칼로리', note:'체중과 운동 강도에 따라 실제 소모량은 달라집니다.', fields:[f('minutes','운동시간','분',45),f('kcalPerHour','시간당 소모 칼로리','kcal',500)] },
  { id:'health_waist_hip_ratio', name:'허리 엉덩이 비율 계산기', category:'health', icon:'🏃', mode:'ratio', description:'허리둘레를 엉덩이둘레로 나누어 비율을 계산합니다.', formula:'허리둘레 ÷ 엉덩이둘레', note:'의학적 판단은 전문기관 기준과 상담이 필요합니다.', fields:[f('a','허리둘레','cm',82),f('b','엉덩이둘레','cm',96)], meta:{resultLabel:'허리/엉덩이 비율'} },
  { id:'health_quit_smoking_saving', name:'금연 절약액 계산기', category:'health', icon:'🏃', mode:'dailySaving', description:'하루 담배 비용과 금연 일수를 기준으로 절약액을 계산합니다.', formula:'하루 비용 × 금연 일수', note:'건강 개선 효과는 개인별로 다르며 금전 절약액은 참고용입니다.', fields:[f('daily','하루 담배 비용','원',4500),f('days','금연 일수','일',365)] },
  { id:'health_sleep_cycle', name:'수면 사이클 계산기', category:'health', icon:'🏃', mode:'sleepCycle', description:'수면시간을 90분 사이클 기준으로 환산합니다.', formula:'총 수면시간 ÷ 90분', note:'개인별 수면 주기는 다르므로 취침·기상 계획 참고용으로 사용하세요.', fields:[f('hours','수면 시간','시간',7),f('minutes','추가 분','분',30)] },

  { id:'auto_fuel_efficiency', name:'연비 계산기', category:'auto', icon:'🚗', mode:'fuelEfficiency', description:'주행거리와 사용 연료량으로 실제 연비를 계산합니다.', formula:'주행거리 ÷ 사용 연료량', note:'계절, 도로상황, 운전습관에 따라 실연비는 달라집니다.', fields:[f('distance','주행거리','km',420),f('fuel','사용 연료','L',35)] },
  { id:'auto_drivable_distance', name:'주행 가능 거리 계산기', category:'auto', icon:'🚗', mode:'distanceByFuel', description:'남은 연료와 평균연비로 주행 가능 거리를 계산합니다.', formula:'남은 연료 × 평균연비', note:'안전상 실제 가능거리보다 여유를 두고 주유하세요.', fields:[f('fuel','남은 연료','L',25),f('efficiency','평균연비','km/L',12)] },
  { id:'auto_ev_charge_cost', name:'전기차 충전비 계산기', category:'auto', icon:'🚗', mode:'evChargeCost', description:'충전량과 kWh 단가로 전기차 충전비를 계산합니다.', formula:'충전량 × kWh 단가', note:'급속·완속, 사업자, 시간대별 요금이 달라질 수 있습니다.', fields:[f('kwh','충전량','kWh',50),f('unitPrice','kWh 단가','원',320)] },
  { id:'auto_maintenance_monthly', name:'차량 유지비 계산기', category:'auto', icon:'🚗', mode:'sumAndMonthly', description:'보험료, 자동차세, 정비비, 주유비를 합산해 월평균 유지비를 계산합니다.', formula:'연간 비용 합계 ÷ 12', note:'감가상각과 할부금은 별도 항목으로 추가해야 합니다.', fields:[f('a','연 보험료','원',900000),f('b','연 자동차세','원',520000),f('c','연 정비비','원',600000),f('d','연 주유비','원',2400000)] },
  { id:'auto_tax_monthly', name:'자동차세 월환산 계산기', category:'auto', icon:'🚗', mode:'annualToMonthly', description:'연간 자동차세를 월평균 부담액으로 환산합니다.', formula:'연간 자동차세 ÷ 12', note:'차종, 배기량, 연식, 감면 조건에 따라 실제 자동차세는 달라질 수 있습니다.', fields:[f('annual','연간 자동차세','원',520000)] },

  { id:'education_correct_rate', name:'정답률 계산기', category:'education', icon:'📚', mode:'percentageOf', description:'전체 문항 중 정답 문항 비율을 계산합니다.', formula:'정답 수 ÷ 전체 문항 수 × 100', note:'부분점수가 있으면 별도 기준을 적용해야 합니다.', fields:[f('part','정답 수','개',36),f('total','전체 문항 수','개',40)], meta:{resultLabel:'정답률'} },
  { id:'education_error_rate', name:'오답률 계산기', category:'education', icon:'📚', mode:'errorRate', description:'전체 문항 중 틀린 문항 비율을 계산합니다.', formula:'오답 수 ÷ 전체 문항 수 × 100', note:'미응답을 오답에 포함할지 기준을 먼저 정하세요.', fields:[f('wrong','오답 수','개',4),f('total','전체 문항 수','개',40)] },
  { id:'education_reading_speed', name:'독서 속도 계산기', category:'education', icon:'📚', mode:'readingSpeed', description:'읽은 쪽수와 소요시간으로 분당 독서량을 계산합니다.', formula:'읽은 쪽수 ÷ 소요시간', note:'문학·전공서·문제집은 난도 차이가 크므로 같은 종류끼리 비교하세요.', fields:[f('pages','읽은 쪽수','쪽',60),f('minutes','소요시간','분',90)] },
  { id:'education_manuscript_pages', name:'원고지 매수 계산기', category:'education', icon:'📚', mode:'manuscriptPages', description:'글자수를 200자 원고지 기준 매수로 환산합니다.', formula:'글자수 ÷ 200', note:'공백 포함 여부와 학교·기관 제출 기준을 확인하세요.', fields:[f('chars','글자수','자',1800)] },
  { id:'education_absence_allowance', name:'결석 가능 횟수 계산기', category:'education', icon:'📚', mode:'absenceAllowance', description:'총 수업일과 최소 출석률 기준으로 가능한 결석일을 계산합니다.', formula:'총 수업일 × (1 - 최소 출석률)', note:'지각·조퇴가 결석으로 환산되는 기준은 기관별로 다릅니다.', fields:[f('total','총 수업일','일',100),f('minRate','최소 출석률','%',80),f('used','이미 결석한 일수','일',5)] },

  { id:'business_average_order_value', name:'객단가 계산기', category:'business', icon:'📈', mode:'averageOrderValue', description:'총 매출을 주문 수로 나누어 평균 주문금액을 계산합니다.', formula:'총 매출 ÷ 주문 수', note:'환불·취소 주문을 제외한 기준으로 계산해야 정확합니다.', fields:[f('revenue','총 매출','원',12000000),f('orders','주문 수','건',300)] },
  { id:'business_cpa', name:'광고 CPA 계산기', category:'business', icon:'📈', mode:'averageOrderValue', description:'광고비를 전환 수로 나누어 전환 1건당 비용을 계산합니다.', formula:'광고비 ÷ 전환 수', note:'문의, 가입, 구매 등 전환 기준을 명확히 해야 합니다.', fields:[f('revenue','광고비','원',1000000),f('orders','전환 수','건',50)], meta:{resultLabel:'전환 1건당 비용'} },
  { id:'business_labor_cost_rate', name:'인건비율 계산기', category:'business', icon:'📈', mode:'percentageOf', description:'매출 대비 인건비 비율을 계산합니다.', formula:'인건비 ÷ 매출 × 100', note:'4대보험 회사부담금과 퇴직급여 충당분을 포함할지 기준을 정하세요.', fields:[f('part','인건비','원',4500000),f('total','매출','원',20000000)], meta:{resultLabel:'인건비율'} },
  { id:'business_cost_rate', name:'원가율 계산기', category:'business', icon:'📈', mode:'percentageOf', description:'매출 대비 원가 비율을 계산합니다.', formula:'매출원가 ÷ 매출 × 100', note:'배송비, 플랫폼 수수료, 포장비를 원가에 넣을지 구분해야 합니다.', fields:[f('part','매출원가','원',9000000),f('total','매출','원',20000000)], meta:{resultLabel:'원가율'} },
  { id:'business_mrr', name:'구독 서비스 MRR 계산기', category:'business', icon:'📈', mode:'multiply', description:'월 구독료와 유료 구독자 수로 월 반복매출을 계산합니다.', formula:'월 구독료 × 구독자 수', note:'연 결제 환산, 할인, 해지 예정 고객은 별도 기준으로 관리해야 합니다.', fields:[f('a','월 구독료','원',29000),f('b','유료 구독자 수','명',120)], meta:{resultLabel:'MRR'} },

  { id:'shopping_card_discount', name:'카드 청구할인 계산기', category:'shopping', icon:'🛒', mode:'discountPrice', description:'결제금액과 청구할인율로 실제 청구 예상액을 계산합니다.', formula:'결제금액 × (1 - 할인율)', note:'전월 실적, 할인한도, 제외 가맹점 조건을 확인하세요.', fields:[f('price','결제금액','원',300000),f('discountRate','청구할인율','%',7)] },
  { id:'shopping_installment_monthly', name:'무이자 할부 월납입 계산기', category:'shopping', icon:'🛒', mode:'divideAmount', description:'결제금액을 무이자 할부개월수로 나누어 월 납입액을 계산합니다.', formula:'결제금액 ÷ 할부개월수', note:'무이자 여부와 부분무이자 조건을 카드사에서 확인하세요.', fields:[f('total','결제금액','원',600000),f('count','할부개월수','개월',6)], meta:{resultLabel:'월 납입액'} },
  { id:'shopping_shipping_unit', name:'배송비 포함 단가 계산기', category:'shopping', icon:'🛒', mode:'bundleUnitPrice', description:'상품금액과 배송비를 합산해 개당 실제 단가를 계산합니다.', formula:'(상품금액 + 배송비) ÷ 수량', note:'묶음상품 비교 시 같은 용량 단위로 비교하세요.', fields:[f('total','상품금액','원',24000),f('shipping','배송비','원',3000),f('quantity','수량','개',3)] },
  { id:'shopping_refund_amount', name:'환불 금액 계산기', category:'shopping', icon:'🛒', mode:'refundAmount', description:'결제금액에서 사용금액과 반품비를 빼 예상 환불액을 계산합니다.', formula:'결제금액 - 사용금액 - 반품비', note:'쿠폰, 포인트, 무료배송 조건 변경으로 실제 환불액은 달라질 수 있습니다.', fields:[f('paid','결제금액','원',80000),f('used','사용 또는 차감금액','원',0),f('fee','반품비','원',3000)] },
  { id:'shopping_grocery_total', name:'장보기 총액 계산기', category:'shopping', icon:'🛒', mode:'sumFive', description:'장보기 항목별 금액을 합산해 총액을 계산합니다.', formula:'항목별 금액 합계', note:'할인쿠폰과 포인트 사용액은 별도로 차감하세요.', fields:[f('a','식료품','원',32000),f('b','생활용품','원',18000),f('c','간식','원',12000),f('d','음료','원',8000),f('e','기타','원',5000)] },

  { id:'unit_inch_cm', name:'인치 cm 변환기', category:'unit', icon:'📐', mode:'inchToCm', description:'인치를 센티미터로 변환합니다.', formula:'인치 × 2.54', note:'모니터, 캐리어, 의류 사이즈 확인에 사용할 수 있습니다.', fields:[f('inch','인치','in',15)] },
  { id:'unit_mile_km', name:'마일 km 변환기', category:'unit', icon:'📐', mode:'mileToKm', description:'마일을 킬로미터로 변환합니다.', formula:'마일 × 1.609344', note:'해외 거리 정보나 자동차 주행거리 확인에 사용할 수 있습니다.', fields:[f('mile','마일','mile',10)] },
  { id:'unit_lb_kg', name:'파운드 kg 변환기', category:'unit', icon:'📐', mode:'lbToKg', description:'파운드를 킬로그램으로 변환합니다.', formula:'lb ÷ 2.20462', note:'해외 직구 무게와 배송비 확인에 사용할 수 있습니다.', fields:[f('lb','파운드','lb',22)] },
  { id:'unit_fahrenheit_celsius', name:'화씨 섭씨 변환기', category:'unit', icon:'📐', mode:'fahrenheitCelsius', description:'화씨 온도를 섭씨로 변환합니다.', formula:'(℉ - 32) × 5 ÷ 9', note:'해외 날씨와 조리 온도 확인에 사용할 수 있습니다.', fields:[f('fahrenheit','화씨','℉',77)] },
  { id:'unit_hour_minute', name:'시간 분 변환기', category:'unit', icon:'📐', mode:'hourToMinute', description:'시간을 분 단위로 변환합니다.', formula:'시간 × 60', note:'근무시간, 운동시간, 학습시간 계산에 사용할 수 있습니다.', fields:[f('hour','시간','시간',2.5)] },

  { id:'travel_lodging_split', name:'숙박비 분담 계산기', category:'travel', icon:'✈️', mode:'splitCost', description:'총 숙박비를 인원수로 나누어 1인 부담액을 계산합니다.', formula:'숙박비 총액 ÷ 인원수', note:'객실별 사용일수나 인원 차이가 있으면 별도 조정하세요.', fields:[f('total','숙박비 총액','원',640000),f('people','인원수','명',4)] },
  { id:'travel_tip', name:'팁 계산기', category:'travel', icon:'✈️', mode:'rateAmount', description:'결제금액과 팁 비율로 팁 금액을 계산합니다.', formula:'결제금액 × 팁 비율', note:'국가별 팁 문화와 서비스차지 포함 여부를 확인하세요.', fields:[f('base','결제금액','원',85000),f('rate','팁 비율','%',15)], meta:{resultLabel:'팁 금액'} },
  { id:'travel_card_fee', name:'해외 결제 수수료 계산기', category:'travel', icon:'✈️', mode:'rateAmount', description:'해외 결제금액과 수수료율로 예상 수수료를 계산합니다.', formula:'결제금액 × 수수료율', note:'카드사, 브랜드사, 환율 적용 시점에 따라 실제 청구액은 달라질 수 있습니다.', fields:[f('base','해외 결제금액','원',300000),f('rate','수수료율','%',1.5)], meta:{resultLabel:'예상 수수료'} },
  { id:'travel_duty_free_excess', name:'면세 한도 초과금액 계산기', category:'travel', icon:'✈️', mode:'excessAmount', description:'구매금액에서 면세 한도를 초과한 금액을 계산합니다.', formula:'구매금액 - 면세한도', note:'품목별 별도 한도와 신고 기준은 관세청 기준을 확인하세요.', fields:[f('amount','구매금액','원',1200000),f('limit','면세한도','원',800000)] },
  { id:'travel_mileage_value', name:'마일리지 가치 계산기', category:'travel', icon:'✈️', mode:'unitCompare', description:'항공권 현금가를 사용 마일리지로 나누어 1마일 가치를 계산합니다.', formula:'항공권 현금가 ÷ 사용 마일리지', note:'유류할증료, 세금, 좌석 등급에 따라 실제 가치는 달라질 수 있습니다.', fields:[f('price','항공권 현금가','원',650000),f('amount','사용 마일리지','마일',35000)] },
];
